<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: INTERACT_WORD_V2.proto

namespace app\Protobuf\InteractWordV2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>BaseOption</code>
 */
class BaseOption extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool need_mystery = 1;</code>
     */
    protected $need_mystery = false;
    /**
     * Generated from protobuf field <code>.RiskCtrl risk_ctrl = 2;</code>
     */
    protected $risk_ctrl = null;
    /**
     * Generated from protobuf field <code>.RoomAnonCtrl room_anon_ctrl = 3;</code>
     */
    protected $room_anon_ctrl = null;
    /**
     * Generated from protobuf field <code>repeated .RiskPolicyEnum risk_ctrl_handles = 4;</code>
     */
    private $risk_ctrl_handles;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $need_mystery
     *     @type \app\Protobuf\InteractWordV2\RiskCtrl $risk_ctrl
     *     @type \app\Protobuf\InteractWordV2\RoomAnonCtrl $room_anon_ctrl
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $risk_ctrl_handles
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\INTERACTWORDV2::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool need_mystery = 1;</code>
     * @return bool
     */
    public function getNeedMystery()
    {
        return $this->need_mystery;
    }

    /**
     * Generated from protobuf field <code>bool need_mystery = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setNeedMystery($var)
    {
        GPBUtil::checkBool($var);
        $this->need_mystery = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.RiskCtrl risk_ctrl = 2;</code>
     * @return \app\Protobuf\InteractWordV2\RiskCtrl|null
     */
    public function getRiskCtrl()
    {
        return $this->risk_ctrl;
    }

    public function hasRiskCtrl()
    {
        return isset($this->risk_ctrl);
    }

    public function clearRiskCtrl()
    {
        unset($this->risk_ctrl);
    }

    /**
     * Generated from protobuf field <code>.RiskCtrl risk_ctrl = 2;</code>
     * @param \app\Protobuf\InteractWordV2\RiskCtrl $var
     * @return $this
     */
    public function setRiskCtrl($var)
    {
        GPBUtil::checkMessage($var, \app\Protobuf\InteractWordV2\RiskCtrl::class);
        $this->risk_ctrl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.RoomAnonCtrl room_anon_ctrl = 3;</code>
     * @return \app\Protobuf\InteractWordV2\RoomAnonCtrl|null
     */
    public function getRoomAnonCtrl()
    {
        return $this->room_anon_ctrl;
    }

    public function hasRoomAnonCtrl()
    {
        return isset($this->room_anon_ctrl);
    }

    public function clearRoomAnonCtrl()
    {
        unset($this->room_anon_ctrl);
    }

    /**
     * Generated from protobuf field <code>.RoomAnonCtrl room_anon_ctrl = 3;</code>
     * @param \app\Protobuf\InteractWordV2\RoomAnonCtrl $var
     * @return $this
     */
    public function setRoomAnonCtrl($var)
    {
        GPBUtil::checkMessage($var, \app\Protobuf\InteractWordV2\RoomAnonCtrl::class);
        $this->room_anon_ctrl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .RiskPolicyEnum risk_ctrl_handles = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRiskCtrlHandles()
    {
        return $this->risk_ctrl_handles;
    }

    /**
     * Generated from protobuf field <code>repeated .RiskPolicyEnum risk_ctrl_handles = 4;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRiskCtrlHandles($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \app\Protobuf\InteractWordV2\RiskPolicyEnum::class);
        $this->risk_ctrl_handles = $arr;

        return $this;
    }

}

