<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: INTERACT_WORD_V2.proto

namespace app\Protobuf\InteractWordV2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Base</code>
 */
class Base extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string face = 2;</code>
     */
    protected $face = '';
    /**
     * Generated from protobuf field <code>int32 name_color = 3;</code>
     */
    protected $name_color = 0;
    /**
     * Generated from protobuf field <code>bool is_mystery = 4;</code>
     */
    protected $is_mystery = false;
    /**
     * Generated from protobuf field <code>.RiskCtrlInfo risk_ctrl_info = 5;</code>
     */
    protected $risk_ctrl_info = null;
    /**
     * Generated from protobuf field <code>.AccountInfo origin_info = 6;</code>
     */
    protected $origin_info = null;
    /**
     * Generated from protobuf field <code>.OfficialInfo official_info = 7;</code>
     */
    protected $official_info = null;
    /**
     * Generated from protobuf field <code>string name_color_str = 8;</code>
     */
    protected $name_color_str = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type string $face
     *     @type int $name_color
     *     @type bool $is_mystery
     *     @type \app\Protobuf\InteractWordV2\RiskCtrlInfo $risk_ctrl_info
     *     @type \app\Protobuf\InteractWordV2\AccountInfo $origin_info
     *     @type \app\Protobuf\InteractWordV2\OfficialInfo $official_info
     *     @type string $name_color_str
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\INTERACTWORDV2::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string face = 2;</code>
     * @return string
     */
    public function getFace()
    {
        return $this->face;
    }

    /**
     * Generated from protobuf field <code>string face = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFace($var)
    {
        GPBUtil::checkString($var, True);
        $this->face = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 name_color = 3;</code>
     * @return int
     */
    public function getNameColor()
    {
        return $this->name_color;
    }

    /**
     * Generated from protobuf field <code>int32 name_color = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setNameColor($var)
    {
        GPBUtil::checkInt32($var);
        $this->name_color = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_mystery = 4;</code>
     * @return bool
     */
    public function getIsMystery()
    {
        return $this->is_mystery;
    }

    /**
     * Generated from protobuf field <code>bool is_mystery = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsMystery($var)
    {
        GPBUtil::checkBool($var);
        $this->is_mystery = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.RiskCtrlInfo risk_ctrl_info = 5;</code>
     * @return \app\Protobuf\InteractWordV2\RiskCtrlInfo|null
     */
    public function getRiskCtrlInfo()
    {
        return $this->risk_ctrl_info;
    }

    public function hasRiskCtrlInfo()
    {
        return isset($this->risk_ctrl_info);
    }

    public function clearRiskCtrlInfo()
    {
        unset($this->risk_ctrl_info);
    }

    /**
     * Generated from protobuf field <code>.RiskCtrlInfo risk_ctrl_info = 5;</code>
     * @param \app\Protobuf\InteractWordV2\RiskCtrlInfo $var
     * @return $this
     */
    public function setRiskCtrlInfo($var)
    {
        GPBUtil::checkMessage($var, \app\Protobuf\InteractWordV2\RiskCtrlInfo::class);
        $this->risk_ctrl_info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.AccountInfo origin_info = 6;</code>
     * @return \app\Protobuf\InteractWordV2\AccountInfo|null
     */
    public function getOriginInfo()
    {
        return $this->origin_info;
    }

    public function hasOriginInfo()
    {
        return isset($this->origin_info);
    }

    public function clearOriginInfo()
    {
        unset($this->origin_info);
    }

    /**
     * Generated from protobuf field <code>.AccountInfo origin_info = 6;</code>
     * @param \app\Protobuf\InteractWordV2\AccountInfo $var
     * @return $this
     */
    public function setOriginInfo($var)
    {
        GPBUtil::checkMessage($var, \app\Protobuf\InteractWordV2\AccountInfo::class);
        $this->origin_info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.OfficialInfo official_info = 7;</code>
     * @return \app\Protobuf\InteractWordV2\OfficialInfo|null
     */
    public function getOfficialInfo()
    {
        return $this->official_info;
    }

    public function hasOfficialInfo()
    {
        return isset($this->official_info);
    }

    public function clearOfficialInfo()
    {
        unset($this->official_info);
    }

    /**
     * Generated from protobuf field <code>.OfficialInfo official_info = 7;</code>
     * @param \app\Protobuf\InteractWordV2\OfficialInfo $var
     * @return $this
     */
    public function setOfficialInfo($var)
    {
        GPBUtil::checkMessage($var, \app\Protobuf\InteractWordV2\OfficialInfo::class);
        $this->official_info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name_color_str = 8;</code>
     * @return string
     */
    public function getNameColorStr()
    {
        return $this->name_color_str;
    }

    /**
     * Generated from protobuf field <code>string name_color_str = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setNameColorStr($var)
    {
        GPBUtil::checkString($var, True);
        $this->name_color_str = $var;

        return $this;
    }

}

