<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: INTERACT_WORD_V2.proto

namespace app\Protobuf\InteractWordV2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ContributionInfoV2</code>
 */
class ContributionInfoV2 extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 grade = 1;</code>
     */
    protected $grade = 0;
    /**
     * Generated from protobuf field <code>string rank_type = 2;</code>
     */
    protected $rank_type = '';
    /**
     * Generated from protobuf field <code>string text = 3;</code>
     */
    protected $text = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $grade
     *     @type string $rank_type
     *     @type string $text
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\INTERACTWORDV2::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 grade = 1;</code>
     * @return int|string
     */
    public function getGrade()
    {
        return $this->grade;
    }

    /**
     * Generated from protobuf field <code>uint64 grade = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setGrade($var)
    {
        GPBUtil::checkUint64($var);
        $this->grade = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string rank_type = 2;</code>
     * @return string
     */
    public function getRankType()
    {
        return $this->rank_type;
    }

    /**
     * Generated from protobuf field <code>string rank_type = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRankType($var)
    {
        GPBUtil::checkString($var, True);
        $this->rank_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string text = 3;</code>
     * @return string
     */
    public function getText()
    {
        return $this->text;
    }

    /**
     * Generated from protobuf field <code>string text = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setText($var)
    {
        GPBUtil::checkString($var, True);
        $this->text = $var;

        return $this;
    }

}

