<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: INTERACT_WORD_V2.proto

namespace app\Protobuf\InteractWordV2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>FansMedalInfo</code>
 */
class FansMedalInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 target_id = 1;</code>
     */
    protected $target_id = 0;
    /**
     * Generated from protobuf field <code>int64 medal_level = 2;</code>
     */
    protected $medal_level = 0;
    /**
     * Generated from protobuf field <code>string medal_name = 3;</code>
     */
    protected $medal_name = '';
    /**
     * Generated from protobuf field <code>int64 medal_color = 4;</code>
     */
    protected $medal_color = 0;
    /**
     * Generated from protobuf field <code>int64 medal_color_start = 5;</code>
     */
    protected $medal_color_start = 0;
    /**
     * Generated from protobuf field <code>int64 medal_color_end = 6;</code>
     */
    protected $medal_color_end = 0;
    /**
     * Generated from protobuf field <code>int64 medal_color_border = 7;</code>
     */
    protected $medal_color_border = 0;
    /**
     * Generated from protobuf field <code>int64 is_lighted = 8;</code>
     */
    protected $is_lighted = 0;
    /**
     * Generated from protobuf field <code>int64 guard_level = 9;</code>
     */
    protected $guard_level = 0;
    /**
     * Generated from protobuf field <code>string special = 10;</code>
     */
    protected $special = '';
    /**
     * Generated from protobuf field <code>int64 icon_id = 11;</code>
     */
    protected $icon_id = 0;
    /**
     * Generated from protobuf field <code>int64 anchor_roomid = 12;</code>
     */
    protected $anchor_roomid = 0;
    /**
     * Generated from protobuf field <code>int64 score = 13;</code>
     */
    protected $score = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $target_id
     *     @type int|string $medal_level
     *     @type string $medal_name
     *     @type int|string $medal_color
     *     @type int|string $medal_color_start
     *     @type int|string $medal_color_end
     *     @type int|string $medal_color_border
     *     @type int|string $is_lighted
     *     @type int|string $guard_level
     *     @type string $special
     *     @type int|string $icon_id
     *     @type int|string $anchor_roomid
     *     @type int|string $score
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\INTERACTWORDV2::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 target_id = 1;</code>
     * @return int|string
     */
    public function getTargetId()
    {
        return $this->target_id;
    }

    /**
     * Generated from protobuf field <code>int64 target_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTargetId($var)
    {
        GPBUtil::checkInt64($var);
        $this->target_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 medal_level = 2;</code>
     * @return int|string
     */
    public function getMedalLevel()
    {
        return $this->medal_level;
    }

    /**
     * Generated from protobuf field <code>int64 medal_level = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMedalLevel($var)
    {
        GPBUtil::checkInt64($var);
        $this->medal_level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string medal_name = 3;</code>
     * @return string
     */
    public function getMedalName()
    {
        return $this->medal_name;
    }

    /**
     * Generated from protobuf field <code>string medal_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMedalName($var)
    {
        GPBUtil::checkString($var, True);
        $this->medal_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 medal_color = 4;</code>
     * @return int|string
     */
    public function getMedalColor()
    {
        return $this->medal_color;
    }

    /**
     * Generated from protobuf field <code>int64 medal_color = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMedalColor($var)
    {
        GPBUtil::checkInt64($var);
        $this->medal_color = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 medal_color_start = 5;</code>
     * @return int|string
     */
    public function getMedalColorStart()
    {
        return $this->medal_color_start;
    }

    /**
     * Generated from protobuf field <code>int64 medal_color_start = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMedalColorStart($var)
    {
        GPBUtil::checkInt64($var);
        $this->medal_color_start = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 medal_color_end = 6;</code>
     * @return int|string
     */
    public function getMedalColorEnd()
    {
        return $this->medal_color_end;
    }

    /**
     * Generated from protobuf field <code>int64 medal_color_end = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMedalColorEnd($var)
    {
        GPBUtil::checkInt64($var);
        $this->medal_color_end = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 medal_color_border = 7;</code>
     * @return int|string
     */
    public function getMedalColorBorder()
    {
        return $this->medal_color_border;
    }

    /**
     * Generated from protobuf field <code>int64 medal_color_border = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMedalColorBorder($var)
    {
        GPBUtil::checkInt64($var);
        $this->medal_color_border = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 is_lighted = 8;</code>
     * @return int|string
     */
    public function getIsLighted()
    {
        return $this->is_lighted;
    }

    /**
     * Generated from protobuf field <code>int64 is_lighted = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setIsLighted($var)
    {
        GPBUtil::checkInt64($var);
        $this->is_lighted = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 guard_level = 9;</code>
     * @return int|string
     */
    public function getGuardLevel()
    {
        return $this->guard_level;
    }

    /**
     * Generated from protobuf field <code>int64 guard_level = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setGuardLevel($var)
    {
        GPBUtil::checkInt64($var);
        $this->guard_level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string special = 10;</code>
     * @return string
     */
    public function getSpecial()
    {
        return $this->special;
    }

    /**
     * Generated from protobuf field <code>string special = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setSpecial($var)
    {
        GPBUtil::checkString($var, True);
        $this->special = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 icon_id = 11;</code>
     * @return int|string
     */
    public function getIconId()
    {
        return $this->icon_id;
    }

    /**
     * Generated from protobuf field <code>int64 icon_id = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setIconId($var)
    {
        GPBUtil::checkInt64($var);
        $this->icon_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 anchor_roomid = 12;</code>
     * @return int|string
     */
    public function getAnchorRoomid()
    {
        return $this->anchor_roomid;
    }

    /**
     * Generated from protobuf field <code>int64 anchor_roomid = 12;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAnchorRoomid($var)
    {
        GPBUtil::checkInt64($var);
        $this->anchor_roomid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 score = 13;</code>
     * @return int|string
     */
    public function getScore()
    {
        return $this->score;
    }

    /**
     * Generated from protobuf field <code>int64 score = 13;</code>
     * @param int|string $var
     * @return $this
     */
    public function setScore($var)
    {
        GPBUtil::checkInt64($var);
        $this->score = $var;

        return $this;
    }

}

