<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: INTERACT_WORD_V2.proto

namespace app\Protobuf\InteractWordV2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GroupMedalBrief</code>
 */
class GroupMedalBrief extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 medal_id = 1;</code>
     */
    protected $medal_id = 0;
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>uint64 is_lighted = 3;</code>
     */
    protected $is_lighted = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $medal_id
     *     @type string $name
     *     @type int|string $is_lighted
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\INTERACTWORDV2::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 medal_id = 1;</code>
     * @return int|string
     */
    public function getMedalId()
    {
        return $this->medal_id;
    }

    /**
     * Generated from protobuf field <code>uint64 medal_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMedalId($var)
    {
        GPBUtil::checkUint64($var);
        $this->medal_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 is_lighted = 3;</code>
     * @return int|string
     */
    public function getIsLighted()
    {
        return $this->is_lighted;
    }

    /**
     * Generated from protobuf field <code>uint64 is_lighted = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setIsLighted($var)
    {
        GPBUtil::checkUint64($var);
        $this->is_lighted = $var;

        return $this;
    }

}

