<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: INTERACT_WORD_V2.proto

namespace app\Protobuf\InteractWordV2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GuardLeader</code>
 */
class GuardLeader extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool is_guard_leader = 1;</code>
     */
    protected $is_guard_leader = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $is_guard_leader
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\INTERACTWORDV2::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool is_guard_leader = 1;</code>
     * @return bool
     */
    public function getIsGuardLeader()
    {
        return $this->is_guard_leader;
    }

    /**
     * Generated from protobuf field <code>bool is_guard_leader = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsGuardLeader($var)
    {
        GPBUtil::checkBool($var);
        $this->is_guard_leader = $var;

        return $this;
    }

}

