<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: INTERACT_WORD_V2.proto

namespace app\Protobuf\InteractWordV2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GuardOption</code>
 */
class GuardOption extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 ruid = 1;</code>
     */
    protected $ruid = 0;
    /**
     * Generated from protobuf field <code>bool use_local_cache = 2;</code>
     */
    protected $use_local_cache = false;
    /**
     * Generated from protobuf field <code>bool strong_depend = 3;</code>
     */
    protected $strong_depend = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $ruid
     *     @type bool $use_local_cache
     *     @type bool $strong_depend
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\INTERACTWORDV2::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 ruid = 1;</code>
     * @return int|string
     */
    public function getRuid()
    {
        return $this->ruid;
    }

    /**
     * Generated from protobuf field <code>int64 ruid = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRuid($var)
    {
        GPBUtil::checkInt64($var);
        $this->ruid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool use_local_cache = 2;</code>
     * @return bool
     */
    public function getUseLocalCache()
    {
        return $this->use_local_cache;
    }

    /**
     * Generated from protobuf field <code>bool use_local_cache = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setUseLocalCache($var)
    {
        GPBUtil::checkBool($var);
        $this->use_local_cache = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool strong_depend = 3;</code>
     * @return bool
     */
    public function getStrongDepend()
    {
        return $this->strong_depend;
    }

    /**
     * Generated from protobuf field <code>bool strong_depend = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setStrongDepend($var)
    {
        GPBUtil::checkBool($var);
        $this->strong_depend = $var;

        return $this;
    }

}

