<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: INTERACT_WORD_V2.proto

namespace app\Protobuf\InteractWordV2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GuardLeaderOption</code>
 */
class GuardLeaderOption extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 ruid = 1;</code>
     */
    protected $ruid = 0;
    /**
     * Generated from protobuf field <code>int64 room_id = 2;</code>
     */
    protected $room_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $ruid
     *     @type int|string $room_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\INTERACTWORDV2::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 ruid = 1;</code>
     * @return int|string
     */
    public function getRuid()
    {
        return $this->ruid;
    }

    /**
     * Generated from protobuf field <code>int64 ruid = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRuid($var)
    {
        GPBUtil::checkInt64($var);
        $this->ruid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 room_id = 2;</code>
     * @return int|string
     */
    public function getRoomId()
    {
        return $this->room_id;
    }

    /**
     * Generated from protobuf field <code>int64 room_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRoomId($var)
    {
        GPBUtil::checkInt64($var);
        $this->room_id = $var;

        return $this;
    }

}

