<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: INTERACT_WORD_V2.proto

namespace app\Protobuf\InteractWordV2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Guard</code>
 */
class Guard extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 level = 1;</code>
     */
    protected $level = 0;
    /**
     * Generated from protobuf field <code>string expired_str = 2;</code>
     */
    protected $expired_str = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $level
     *     @type string $expired_str
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\INTERACTWORDV2::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 level = 1;</code>
     * @return int|string
     */
    public function getLevel()
    {
        return $this->level;
    }

    /**
     * Generated from protobuf field <code>int64 level = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLevel($var)
    {
        GPBUtil::checkInt64($var);
        $this->level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string expired_str = 2;</code>
     * @return string
     */
    public function getExpiredStr()
    {
        return $this->expired_str;
    }

    /**
     * Generated from protobuf field <code>string expired_str = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setExpiredStr($var)
    {
        GPBUtil::checkString($var, True);
        $this->expired_str = $var;

        return $this;
    }

}

