<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: INTERACT_WORD_V2.proto

namespace app\Protobuf\InteractWordV2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>InteractWordV2</code>
 */
class InteractWordV2 extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 uid = 1;</code>
     */
    protected $uid = 0;
    /**
     * Generated from protobuf field <code>string uname = 2;</code>
     */
    protected $uname = '';
    /**
     * Generated from protobuf field <code>string uname_color = 3;</code>
     */
    protected $uname_color = '';
    /**
     * Generated from protobuf field <code>repeated uint64 identities = 4;</code>
     */
    private $identities;
    /**
     * Generated from protobuf field <code>uint64 msg_type = 5;</code>
     */
    protected $msg_type = 0;
    /**
     * Generated from protobuf field <code>uint64 roomid = 6;</code>
     */
    protected $roomid = 0;
    /**
     * Generated from protobuf field <code>uint64 timestamp = 7;</code>
     */
    protected $timestamp = 0;
    /**
     * Generated from protobuf field <code>uint64 score = 8;</code>
     */
    protected $score = 0;
    /**
     * Generated from protobuf field <code>.FansMedalInfo fans_medal = 9;</code>
     */
    protected $fans_medal = null;
    /**
     * Generated from protobuf field <code>uint64 is_spread = 10;</code>
     */
    protected $is_spread = 0;
    /**
     * Generated from protobuf field <code>string spread_info = 11;</code>
     */
    protected $spread_info = '';
    /**
     * Generated from protobuf field <code>.ContributionInfo contribution = 12;</code>
     */
    protected $contribution = null;
    /**
     * Generated from protobuf field <code>string spread_desc = 13;</code>
     */
    protected $spread_desc = '';
    /**
     * Generated from protobuf field <code>uint64 tail_icon = 14;</code>
     */
    protected $tail_icon = 0;
    /**
     * Generated from protobuf field <code>uint64 trigger_time = 15;</code>
     */
    protected $trigger_time = 0;
    /**
     * Generated from protobuf field <code>uint64 privilege_type = 16;</code>
     */
    protected $privilege_type = 0;
    /**
     * Generated from protobuf field <code>uint64 core_user_type = 17;</code>
     */
    protected $core_user_type = 0;
    /**
     * Generated from protobuf field <code>string tail_text = 18;</code>
     */
    protected $tail_text = '';
    /**
     * Generated from protobuf field <code>.ContributionInfoV2 contribution_v2 = 19;</code>
     */
    protected $contribution_v2 = null;
    /**
     * Generated from protobuf field <code>.GroupMedalBrief group_medal = 20;</code>
     */
    protected $group_medal = null;
    /**
     * Generated from protobuf field <code>bool is_mystery = 21;</code>
     */
    protected $is_mystery = false;
    /**
     * Generated from protobuf field <code>.UserInfo uinfo = 22;</code>
     */
    protected $uinfo = null;
    /**
     * Generated from protobuf field <code>.UserAnchorRelation relation_tail = 23;</code>
     */
    protected $relation_tail = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $uid
     *     @type string $uname
     *     @type string $uname_color
     *     @type array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $identities
     *     @type int|string $msg_type
     *     @type int|string $roomid
     *     @type int|string $timestamp
     *     @type int|string $score
     *     @type \app\Protobuf\InteractWordV2\FansMedalInfo $fans_medal
     *     @type int|string $is_spread
     *     @type string $spread_info
     *     @type \app\Protobuf\InteractWordV2\ContributionInfo $contribution
     *     @type string $spread_desc
     *     @type int|string $tail_icon
     *     @type int|string $trigger_time
     *     @type int|string $privilege_type
     *     @type int|string $core_user_type
     *     @type string $tail_text
     *     @type \app\Protobuf\InteractWordV2\ContributionInfoV2 $contribution_v2
     *     @type \app\Protobuf\InteractWordV2\GroupMedalBrief $group_medal
     *     @type bool $is_mystery
     *     @type \app\Protobuf\InteractWordV2\UserInfo $uinfo
     *     @type \app\Protobuf\InteractWordV2\UserAnchorRelation $relation_tail
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\INTERACTWORDV2::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 uid = 1;</code>
     * @return int|string
     */
    public function getUid()
    {
        return $this->uid;
    }

    /**
     * Generated from protobuf field <code>uint64 uid = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUid($var)
    {
        GPBUtil::checkUint64($var);
        $this->uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string uname = 2;</code>
     * @return string
     */
    public function getUname()
    {
        return $this->uname;
    }

    /**
     * Generated from protobuf field <code>string uname = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUname($var)
    {
        GPBUtil::checkString($var, True);
        $this->uname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string uname_color = 3;</code>
     * @return string
     */
    public function getUnameColor()
    {
        return $this->uname_color;
    }

    /**
     * Generated from protobuf field <code>string uname_color = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setUnameColor($var)
    {
        GPBUtil::checkString($var, True);
        $this->uname_color = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 identities = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIdentities()
    {
        return $this->identities;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 identities = 4;</code>
     * @param array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIdentities($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT64);
        $this->identities = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 msg_type = 5;</code>
     * @return int|string
     */
    public function getMsgType()
    {
        return $this->msg_type;
    }

    /**
     * Generated from protobuf field <code>uint64 msg_type = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMsgType($var)
    {
        GPBUtil::checkUint64($var);
        $this->msg_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 roomid = 6;</code>
     * @return int|string
     */
    public function getRoomid()
    {
        return $this->roomid;
    }

    /**
     * Generated from protobuf field <code>uint64 roomid = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRoomid($var)
    {
        GPBUtil::checkUint64($var);
        $this->roomid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 timestamp = 7;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>uint64 timestamp = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkUint64($var);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 score = 8;</code>
     * @return int|string
     */
    public function getScore()
    {
        return $this->score;
    }

    /**
     * Generated from protobuf field <code>uint64 score = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setScore($var)
    {
        GPBUtil::checkUint64($var);
        $this->score = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.FansMedalInfo fans_medal = 9;</code>
     * @return \app\Protobuf\InteractWordV2\FansMedalInfo|null
     */
    public function getFansMedal()
    {
        return $this->fans_medal;
    }

    public function hasFansMedal()
    {
        return isset($this->fans_medal);
    }

    public function clearFansMedal()
    {
        unset($this->fans_medal);
    }

    /**
     * Generated from protobuf field <code>.FansMedalInfo fans_medal = 9;</code>
     * @param \app\Protobuf\InteractWordV2\FansMedalInfo $var
     * @return $this
     */
    public function setFansMedal($var)
    {
        GPBUtil::checkMessage($var, \app\Protobuf\InteractWordV2\FansMedalInfo::class);
        $this->fans_medal = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 is_spread = 10;</code>
     * @return int|string
     */
    public function getIsSpread()
    {
        return $this->is_spread;
    }

    /**
     * Generated from protobuf field <code>uint64 is_spread = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setIsSpread($var)
    {
        GPBUtil::checkUint64($var);
        $this->is_spread = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string spread_info = 11;</code>
     * @return string
     */
    public function getSpreadInfo()
    {
        return $this->spread_info;
    }

    /**
     * Generated from protobuf field <code>string spread_info = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setSpreadInfo($var)
    {
        GPBUtil::checkString($var, True);
        $this->spread_info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ContributionInfo contribution = 12;</code>
     * @return \app\Protobuf\InteractWordV2\ContributionInfo|null
     */
    public function getContribution()
    {
        return $this->contribution;
    }

    public function hasContribution()
    {
        return isset($this->contribution);
    }

    public function clearContribution()
    {
        unset($this->contribution);
    }

    /**
     * Generated from protobuf field <code>.ContributionInfo contribution = 12;</code>
     * @param \app\Protobuf\InteractWordV2\ContributionInfo $var
     * @return $this
     */
    public function setContribution($var)
    {
        GPBUtil::checkMessage($var, \app\Protobuf\InteractWordV2\ContributionInfo::class);
        $this->contribution = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string spread_desc = 13;</code>
     * @return string
     */
    public function getSpreadDesc()
    {
        return $this->spread_desc;
    }

    /**
     * Generated from protobuf field <code>string spread_desc = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setSpreadDesc($var)
    {
        GPBUtil::checkString($var, True);
        $this->spread_desc = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 tail_icon = 14;</code>
     * @return int|string
     */
    public function getTailIcon()
    {
        return $this->tail_icon;
    }

    /**
     * Generated from protobuf field <code>uint64 tail_icon = 14;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTailIcon($var)
    {
        GPBUtil::checkUint64($var);
        $this->tail_icon = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 trigger_time = 15;</code>
     * @return int|string
     */
    public function getTriggerTime()
    {
        return $this->trigger_time;
    }

    /**
     * Generated from protobuf field <code>uint64 trigger_time = 15;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTriggerTime($var)
    {
        GPBUtil::checkUint64($var);
        $this->trigger_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 privilege_type = 16;</code>
     * @return int|string
     */
    public function getPrivilegeType()
    {
        return $this->privilege_type;
    }

    /**
     * Generated from protobuf field <code>uint64 privilege_type = 16;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPrivilegeType($var)
    {
        GPBUtil::checkUint64($var);
        $this->privilege_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 core_user_type = 17;</code>
     * @return int|string
     */
    public function getCoreUserType()
    {
        return $this->core_user_type;
    }

    /**
     * Generated from protobuf field <code>uint64 core_user_type = 17;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCoreUserType($var)
    {
        GPBUtil::checkUint64($var);
        $this->core_user_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string tail_text = 18;</code>
     * @return string
     */
    public function getTailText()
    {
        return $this->tail_text;
    }

    /**
     * Generated from protobuf field <code>string tail_text = 18;</code>
     * @param string $var
     * @return $this
     */
    public function setTailText($var)
    {
        GPBUtil::checkString($var, True);
        $this->tail_text = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ContributionInfoV2 contribution_v2 = 19;</code>
     * @return \app\Protobuf\InteractWordV2\ContributionInfoV2|null
     */
    public function getContributionV2()
    {
        return $this->contribution_v2;
    }

    public function hasContributionV2()
    {
        return isset($this->contribution_v2);
    }

    public function clearContributionV2()
    {
        unset($this->contribution_v2);
    }

    /**
     * Generated from protobuf field <code>.ContributionInfoV2 contribution_v2 = 19;</code>
     * @param \app\Protobuf\InteractWordV2\ContributionInfoV2 $var
     * @return $this
     */
    public function setContributionV2($var)
    {
        GPBUtil::checkMessage($var, \app\Protobuf\InteractWordV2\ContributionInfoV2::class);
        $this->contribution_v2 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.GroupMedalBrief group_medal = 20;</code>
     * @return \app\Protobuf\InteractWordV2\GroupMedalBrief|null
     */
    public function getGroupMedal()
    {
        return $this->group_medal;
    }

    public function hasGroupMedal()
    {
        return isset($this->group_medal);
    }

    public function clearGroupMedal()
    {
        unset($this->group_medal);
    }

    /**
     * Generated from protobuf field <code>.GroupMedalBrief group_medal = 20;</code>
     * @param \app\Protobuf\InteractWordV2\GroupMedalBrief $var
     * @return $this
     */
    public function setGroupMedal($var)
    {
        GPBUtil::checkMessage($var, \app\Protobuf\InteractWordV2\GroupMedalBrief::class);
        $this->group_medal = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_mystery = 21;</code>
     * @return bool
     */
    public function getIsMystery()
    {
        return $this->is_mystery;
    }

    /**
     * Generated from protobuf field <code>bool is_mystery = 21;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsMystery($var)
    {
        GPBUtil::checkBool($var);
        $this->is_mystery = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.UserInfo uinfo = 22;</code>
     * @return \app\Protobuf\InteractWordV2\UserInfo|null
     */
    public function getUinfo()
    {
        return $this->uinfo;
    }

    public function hasUinfo()
    {
        return isset($this->uinfo);
    }

    public function clearUinfo()
    {
        unset($this->uinfo);
    }

    /**
     * Generated from protobuf field <code>.UserInfo uinfo = 22;</code>
     * @param \app\Protobuf\InteractWordV2\UserInfo $var
     * @return $this
     */
    public function setUinfo($var)
    {
        GPBUtil::checkMessage($var, \app\Protobuf\InteractWordV2\UserInfo::class);
        $this->uinfo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.UserAnchorRelation relation_tail = 23;</code>
     * @return \app\Protobuf\InteractWordV2\UserAnchorRelation|null
     */
    public function getRelationTail()
    {
        return $this->relation_tail;
    }

    public function hasRelationTail()
    {
        return isset($this->relation_tail);
    }

    public function clearRelationTail()
    {
        unset($this->relation_tail);
    }

    /**
     * Generated from protobuf field <code>.UserAnchorRelation relation_tail = 23;</code>
     * @param \app\Protobuf\InteractWordV2\UserAnchorRelation $var
     * @return $this
     */
    public function setRelationTail($var)
    {
        GPBUtil::checkMessage($var, \app\Protobuf\InteractWordV2\UserAnchorRelation::class);
        $this->relation_tail = $var;

        return $this;
    }

}

