<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: INTERACT_WORD_V2.proto

namespace app\Protobuf\InteractWordV2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Medal</code>
 */
class Medal extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>int64 level = 2;</code>
     */
    protected $level = 0;
    /**
     * Generated from protobuf field <code>int64 color_start = 3;</code>
     */
    protected $color_start = 0;
    /**
     * Generated from protobuf field <code>int64 color_end = 4;</code>
     */
    protected $color_end = 0;
    /**
     * Generated from protobuf field <code>int64 color_border = 5;</code>
     */
    protected $color_border = 0;
    /**
     * Generated from protobuf field <code>int64 color = 6;</code>
     */
    protected $color = 0;
    /**
     * Generated from protobuf field <code>int64 id = 7;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>.HaveMedalType typ = 8;</code>
     */
    protected $typ = 0;
    /**
     * Generated from protobuf field <code>int64 is_light = 9;</code>
     */
    protected $is_light = 0;
    /**
     * Generated from protobuf field <code>int64 ruid = 10;</code>
     */
    protected $ruid = 0;
    /**
     * Generated from protobuf field <code>int64 guard_level = 11;</code>
     */
    protected $guard_level = 0;
    /**
     * Generated from protobuf field <code>int64 score = 12;</code>
     */
    protected $score = 0;
    /**
     * Generated from protobuf field <code>string guard_icon = 13;</code>
     */
    protected $guard_icon = '';
    /**
     * Generated from protobuf field <code>string honor_icon = 14;</code>
     */
    protected $honor_icon = '';
    /**
     * Generated from protobuf field <code>string v2_medal_color_start = 15;</code>
     */
    protected $v2_medal_color_start = '';
    /**
     * Generated from protobuf field <code>string v2_medal_color_end = 16;</code>
     */
    protected $v2_medal_color_end = '';
    /**
     * Generated from protobuf field <code>string v2_medal_color_border = 17;</code>
     */
    protected $v2_medal_color_border = '';
    /**
     * Generated from protobuf field <code>string v2_medal_color_text = 18;</code>
     */
    protected $v2_medal_color_text = '';
    /**
     * Generated from protobuf field <code>string v2_medal_color_level = 19;</code>
     */
    protected $v2_medal_color_level = '';
    /**
     * Generated from protobuf field <code>int64 user_receive_count = 20;</code>
     */
    protected $user_receive_count = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type int|string $level
     *     @type int|string $color_start
     *     @type int|string $color_end
     *     @type int|string $color_border
     *     @type int|string $color
     *     @type int|string $id
     *     @type int $typ
     *     @type int|string $is_light
     *     @type int|string $ruid
     *     @type int|string $guard_level
     *     @type int|string $score
     *     @type string $guard_icon
     *     @type string $honor_icon
     *     @type string $v2_medal_color_start
     *     @type string $v2_medal_color_end
     *     @type string $v2_medal_color_border
     *     @type string $v2_medal_color_text
     *     @type string $v2_medal_color_level
     *     @type int|string $user_receive_count
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\INTERACTWORDV2::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 level = 2;</code>
     * @return int|string
     */
    public function getLevel()
    {
        return $this->level;
    }

    /**
     * Generated from protobuf field <code>int64 level = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLevel($var)
    {
        GPBUtil::checkInt64($var);
        $this->level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 color_start = 3;</code>
     * @return int|string
     */
    public function getColorStart()
    {
        return $this->color_start;
    }

    /**
     * Generated from protobuf field <code>int64 color_start = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setColorStart($var)
    {
        GPBUtil::checkInt64($var);
        $this->color_start = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 color_end = 4;</code>
     * @return int|string
     */
    public function getColorEnd()
    {
        return $this->color_end;
    }

    /**
     * Generated from protobuf field <code>int64 color_end = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setColorEnd($var)
    {
        GPBUtil::checkInt64($var);
        $this->color_end = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 color_border = 5;</code>
     * @return int|string
     */
    public function getColorBorder()
    {
        return $this->color_border;
    }

    /**
     * Generated from protobuf field <code>int64 color_border = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setColorBorder($var)
    {
        GPBUtil::checkInt64($var);
        $this->color_border = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 color = 6;</code>
     * @return int|string
     */
    public function getColor()
    {
        return $this->color;
    }

    /**
     * Generated from protobuf field <code>int64 color = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setColor($var)
    {
        GPBUtil::checkInt64($var);
        $this->color = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 id = 7;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int64 id = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.HaveMedalType typ = 8;</code>
     * @return int
     */
    public function getTyp()
    {
        return $this->typ;
    }

    /**
     * Generated from protobuf field <code>.HaveMedalType typ = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setTyp($var)
    {
        GPBUtil::checkEnum($var, \app\Protobuf\InteractWordV2\HaveMedalType::class);
        $this->typ = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 is_light = 9;</code>
     * @return int|string
     */
    public function getIsLight()
    {
        return $this->is_light;
    }

    /**
     * Generated from protobuf field <code>int64 is_light = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setIsLight($var)
    {
        GPBUtil::checkInt64($var);
        $this->is_light = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 ruid = 10;</code>
     * @return int|string
     */
    public function getRuid()
    {
        return $this->ruid;
    }

    /**
     * Generated from protobuf field <code>int64 ruid = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRuid($var)
    {
        GPBUtil::checkInt64($var);
        $this->ruid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 guard_level = 11;</code>
     * @return int|string
     */
    public function getGuardLevel()
    {
        return $this->guard_level;
    }

    /**
     * Generated from protobuf field <code>int64 guard_level = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setGuardLevel($var)
    {
        GPBUtil::checkInt64($var);
        $this->guard_level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 score = 12;</code>
     * @return int|string
     */
    public function getScore()
    {
        return $this->score;
    }

    /**
     * Generated from protobuf field <code>int64 score = 12;</code>
     * @param int|string $var
     * @return $this
     */
    public function setScore($var)
    {
        GPBUtil::checkInt64($var);
        $this->score = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string guard_icon = 13;</code>
     * @return string
     */
    public function getGuardIcon()
    {
        return $this->guard_icon;
    }

    /**
     * Generated from protobuf field <code>string guard_icon = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setGuardIcon($var)
    {
        GPBUtil::checkString($var, True);
        $this->guard_icon = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string honor_icon = 14;</code>
     * @return string
     */
    public function getHonorIcon()
    {
        return $this->honor_icon;
    }

    /**
     * Generated from protobuf field <code>string honor_icon = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setHonorIcon($var)
    {
        GPBUtil::checkString($var, True);
        $this->honor_icon = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string v2_medal_color_start = 15;</code>
     * @return string
     */
    public function getV2MedalColorStart()
    {
        return $this->v2_medal_color_start;
    }

    /**
     * Generated from protobuf field <code>string v2_medal_color_start = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setV2MedalColorStart($var)
    {
        GPBUtil::checkString($var, True);
        $this->v2_medal_color_start = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string v2_medal_color_end = 16;</code>
     * @return string
     */
    public function getV2MedalColorEnd()
    {
        return $this->v2_medal_color_end;
    }

    /**
     * Generated from protobuf field <code>string v2_medal_color_end = 16;</code>
     * @param string $var
     * @return $this
     */
    public function setV2MedalColorEnd($var)
    {
        GPBUtil::checkString($var, True);
        $this->v2_medal_color_end = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string v2_medal_color_border = 17;</code>
     * @return string
     */
    public function getV2MedalColorBorder()
    {
        return $this->v2_medal_color_border;
    }

    /**
     * Generated from protobuf field <code>string v2_medal_color_border = 17;</code>
     * @param string $var
     * @return $this
     */
    public function setV2MedalColorBorder($var)
    {
        GPBUtil::checkString($var, True);
        $this->v2_medal_color_border = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string v2_medal_color_text = 18;</code>
     * @return string
     */
    public function getV2MedalColorText()
    {
        return $this->v2_medal_color_text;
    }

    /**
     * Generated from protobuf field <code>string v2_medal_color_text = 18;</code>
     * @param string $var
     * @return $this
     */
    public function setV2MedalColorText($var)
    {
        GPBUtil::checkString($var, True);
        $this->v2_medal_color_text = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string v2_medal_color_level = 19;</code>
     * @return string
     */
    public function getV2MedalColorLevel()
    {
        return $this->v2_medal_color_level;
    }

    /**
     * Generated from protobuf field <code>string v2_medal_color_level = 19;</code>
     * @param string $var
     * @return $this
     */
    public function setV2MedalColorLevel($var)
    {
        GPBUtil::checkString($var, True);
        $this->v2_medal_color_level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 user_receive_count = 20;</code>
     * @return int|string
     */
    public function getUserReceiveCount()
    {
        return $this->user_receive_count;
    }

    /**
     * Generated from protobuf field <code>int64 user_receive_count = 20;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserReceiveCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->user_receive_count = $var;

        return $this;
    }

}

