<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: INTERACT_WORD_V2.proto

namespace app\Protobuf\InteractWordV2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>OfficialInfo</code>
 */
class OfficialInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 role = 1;</code>
     */
    protected $role = 0;
    /**
     * Generated from protobuf field <code>string title = 2;</code>
     */
    protected $title = '';
    /**
     * Generated from protobuf field <code>string desc = 3;</code>
     */
    protected $desc = '';
    /**
     * Generated from protobuf field <code>uint64 type = 4;</code>
     */
    protected $type = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $role
     *     @type string $title
     *     @type string $desc
     *     @type int|string $type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\INTERACTWORDV2::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 role = 1;</code>
     * @return int|string
     */
    public function getRole()
    {
        return $this->role;
    }

    /**
     * Generated from protobuf field <code>uint64 role = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRole($var)
    {
        GPBUtil::checkUint64($var);
        $this->role = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string title = 2;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Generated from protobuf field <code>string title = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string desc = 3;</code>
     * @return string
     */
    public function getDesc()
    {
        return $this->desc;
    }

    /**
     * Generated from protobuf field <code>string desc = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDesc($var)
    {
        GPBUtil::checkString($var, True);
        $this->desc = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 type = 4;</code>
     * @return int|string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>uint64 type = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkUint64($var);
        $this->type = $var;

        return $this;
    }

}

