<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: INTERACT_WORD_V2.proto

namespace app\Protobuf\InteractWordV2;

use UnexpectedValueException;

/**
 * Protobuf type <code>RiskPolicyEnum</code>
 */
class RiskPolicyEnum
{
    /**
     * Generated from protobuf enum <code>RP_NORMAL = 0;</code>
     */
    const RP_NORMAL = 0;
    /**
     * Generated from protobuf enum <code>RP_POLICY = 1;</code>
     */
    const RP_POLICY = 1;
    /**
     * Generated from protobuf enum <code>RP_SILENCE = 2;</code>
     */
    const RP_SILENCE = 2;
    /**
     * Generated from protobuf enum <code>RP_CNY = 3;</code>
     */
    const RP_CNY = 3;
    /**
     * Generated from protobuf enum <code>RP_BIGEV = 4;</code>
     */
    const RP_BIGEV = 4;

    private static $valueToName = [
        self::RP_NORMAL => 'RP_NORMAL',
        self::RP_POLICY => 'RP_POLICY',
        self::RP_SILENCE => 'RP_SILENCE',
        self::RP_CNY => 'RP_CNY',
        self::RP_BIGEV => 'RP_BIGEV',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

