<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: INTERACT_WORD_V2.proto

namespace app\Protobuf\InteractWordV2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Title</code>
 */
class Title extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string OldTitleCssId = 1;</code>
     */
    protected $OldTitleCssId = '';
    /**
     * Generated from protobuf field <code>string TitleCssId = 2;</code>
     */
    protected $TitleCssId = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $OldTitleCssId
     *     @type string $TitleCssId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\INTERACTWORDV2::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string OldTitleCssId = 1;</code>
     * @return string
     */
    public function getOldTitleCssId()
    {
        return $this->OldTitleCssId;
    }

    /**
     * Generated from protobuf field <code>string OldTitleCssId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOldTitleCssId($var)
    {
        GPBUtil::checkString($var, True);
        $this->OldTitleCssId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string TitleCssId = 2;</code>
     * @return string
     */
    public function getTitleCssId()
    {
        return $this->TitleCssId;
    }

    /**
     * Generated from protobuf field <code>string TitleCssId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTitleCssId($var)
    {
        GPBUtil::checkString($var, True);
        $this->TitleCssId = $var;

        return $this;
    }

}

