<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: INTERACT_WORD_V2.proto

namespace app\Protobuf\InteractWordV2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>UserAnchorRelation</code>
 */
class UserAnchorRelation extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string tail_icon = 1;</code>
     */
    protected $tail_icon = '';
    /**
     * Generated from protobuf field <code>string tail_guide_text = 2;</code>
     */
    protected $tail_guide_text = '';
    /**
     * Generated from protobuf field <code>uint64 tail_type = 3;</code>
     */
    protected $tail_type = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $tail_icon
     *     @type string $tail_guide_text
     *     @type int|string $tail_type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\INTERACTWORDV2::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string tail_icon = 1;</code>
     * @return string
     */
    public function getTailIcon()
    {
        return $this->tail_icon;
    }

    /**
     * Generated from protobuf field <code>string tail_icon = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTailIcon($var)
    {
        GPBUtil::checkString($var, True);
        $this->tail_icon = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string tail_guide_text = 2;</code>
     * @return string
     */
    public function getTailGuideText()
    {
        return $this->tail_guide_text;
    }

    /**
     * Generated from protobuf field <code>string tail_guide_text = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTailGuideText($var)
    {
        GPBUtil::checkString($var, True);
        $this->tail_guide_text = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 tail_type = 3;</code>
     * @return int|string
     */
    public function getTailType()
    {
        return $this->tail_type;
    }

    /**
     * Generated from protobuf field <code>uint64 tail_type = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTailType($var)
    {
        GPBUtil::checkUint64($var);
        $this->tail_type = $var;

        return $this;
    }

}

