<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: INTERACT_WORD_V2.proto

namespace app\Protobuf\InteractWordV2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>UserInfo</code>
 */
class UserInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 uid = 1;</code>
     */
    protected $uid = 0;
    /**
     * Generated from protobuf field <code>.Base base = 2;</code>
     */
    protected $base = null;
    /**
     * Generated from protobuf field <code>.Medal medal = 3;</code>
     */
    protected $medal = null;
    /**
     * Generated from protobuf field <code>.Wealth wealth = 4;</code>
     */
    protected $wealth = null;
    /**
     * Generated from protobuf field <code>.Title title = 5;</code>
     */
    protected $title = null;
    /**
     * Generated from protobuf field <code>.Guard guard = 6;</code>
     */
    protected $guard = null;
    /**
     * Generated from protobuf field <code>.UserHeadFrame uhead_frame = 7;</code>
     */
    protected $uhead_frame = null;
    /**
     * Generated from protobuf field <code>.GuardLeader guard_leader = 8;</code>
     */
    protected $guard_leader = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $uid
     *     @type \app\Protobuf\InteractWordV2\Base $base
     *     @type \app\Protobuf\InteractWordV2\Medal $medal
     *     @type \app\Protobuf\InteractWordV2\Wealth $wealth
     *     @type \app\Protobuf\InteractWordV2\Title $title
     *     @type \app\Protobuf\InteractWordV2\Guard $guard
     *     @type \app\Protobuf\InteractWordV2\UserHeadFrame $uhead_frame
     *     @type \app\Protobuf\InteractWordV2\GuardLeader $guard_leader
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\INTERACTWORDV2::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 uid = 1;</code>
     * @return int|string
     */
    public function getUid()
    {
        return $this->uid;
    }

    /**
     * Generated from protobuf field <code>uint64 uid = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUid($var)
    {
        GPBUtil::checkUint64($var);
        $this->uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Base base = 2;</code>
     * @return \app\Protobuf\InteractWordV2\Base|null
     */
    public function getBase()
    {
        return $this->base;
    }

    public function hasBase()
    {
        return isset($this->base);
    }

    public function clearBase()
    {
        unset($this->base);
    }

    /**
     * Generated from protobuf field <code>.Base base = 2;</code>
     * @param \app\Protobuf\InteractWordV2\Base $var
     * @return $this
     */
    public function setBase($var)
    {
        GPBUtil::checkMessage($var, \app\Protobuf\InteractWordV2\Base::class);
        $this->base = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Medal medal = 3;</code>
     * @return \app\Protobuf\InteractWordV2\Medal|null
     */
    public function getMedal()
    {
        return $this->medal;
    }

    public function hasMedal()
    {
        return isset($this->medal);
    }

    public function clearMedal()
    {
        unset($this->medal);
    }

    /**
     * Generated from protobuf field <code>.Medal medal = 3;</code>
     * @param \app\Protobuf\InteractWordV2\Medal $var
     * @return $this
     */
    public function setMedal($var)
    {
        GPBUtil::checkMessage($var, \app\Protobuf\InteractWordV2\Medal::class);
        $this->medal = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Wealth wealth = 4;</code>
     * @return \app\Protobuf\InteractWordV2\Wealth|null
     */
    public function getWealth()
    {
        return $this->wealth;
    }

    public function hasWealth()
    {
        return isset($this->wealth);
    }

    public function clearWealth()
    {
        unset($this->wealth);
    }

    /**
     * Generated from protobuf field <code>.Wealth wealth = 4;</code>
     * @param \app\Protobuf\InteractWordV2\Wealth $var
     * @return $this
     */
    public function setWealth($var)
    {
        GPBUtil::checkMessage($var, \app\Protobuf\InteractWordV2\Wealth::class);
        $this->wealth = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Title title = 5;</code>
     * @return \app\Protobuf\InteractWordV2\Title|null
     */
    public function getTitle()
    {
        return $this->title;
    }

    public function hasTitle()
    {
        return isset($this->title);
    }

    public function clearTitle()
    {
        unset($this->title);
    }

    /**
     * Generated from protobuf field <code>.Title title = 5;</code>
     * @param \app\Protobuf\InteractWordV2\Title $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkMessage($var, \app\Protobuf\InteractWordV2\Title::class);
        $this->title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Guard guard = 6;</code>
     * @return \app\Protobuf\InteractWordV2\Guard|null
     */
    public function getGuard()
    {
        return $this->guard;
    }

    public function hasGuard()
    {
        return isset($this->guard);
    }

    public function clearGuard()
    {
        unset($this->guard);
    }

    /**
     * Generated from protobuf field <code>.Guard guard = 6;</code>
     * @param \app\Protobuf\InteractWordV2\Guard $var
     * @return $this
     */
    public function setGuard($var)
    {
        GPBUtil::checkMessage($var, \app\Protobuf\InteractWordV2\Guard::class);
        $this->guard = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.UserHeadFrame uhead_frame = 7;</code>
     * @return \app\Protobuf\InteractWordV2\UserHeadFrame|null
     */
    public function getUheadFrame()
    {
        return $this->uhead_frame;
    }

    public function hasUheadFrame()
    {
        return isset($this->uhead_frame);
    }

    public function clearUheadFrame()
    {
        unset($this->uhead_frame);
    }

    /**
     * Generated from protobuf field <code>.UserHeadFrame uhead_frame = 7;</code>
     * @param \app\Protobuf\InteractWordV2\UserHeadFrame $var
     * @return $this
     */
    public function setUheadFrame($var)
    {
        GPBUtil::checkMessage($var, \app\Protobuf\InteractWordV2\UserHeadFrame::class);
        $this->uhead_frame = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.GuardLeader guard_leader = 8;</code>
     * @return \app\Protobuf\InteractWordV2\GuardLeader|null
     */
    public function getGuardLeader()
    {
        return $this->guard_leader;
    }

    public function hasGuardLeader()
    {
        return isset($this->guard_leader);
    }

    public function clearGuardLeader()
    {
        unset($this->guard_leader);
    }

    /**
     * Generated from protobuf field <code>.GuardLeader guard_leader = 8;</code>
     * @param \app\Protobuf\InteractWordV2\GuardLeader $var
     * @return $this
     */
    public function setGuardLeader($var)
    {
        GPBUtil::checkMessage($var, \app\Protobuf\InteractWordV2\GuardLeader::class);
        $this->guard_leader = $var;

        return $this;
    }

}

