<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: INTERACT_WORD_V2.proto

namespace app\Protobuf\InteractWordV2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Wealth</code>
 */
class Wealth extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 level = 1;</code>
     */
    protected $level = 0;
    /**
     * Generated from protobuf field <code>string dm_icon_key = 2;</code>
     */
    protected $dm_icon_key = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $level
     *     @type string $dm_icon_key
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\INTERACTWORDV2::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 level = 1;</code>
     * @return int|string
     */
    public function getLevel()
    {
        return $this->level;
    }

    /**
     * Generated from protobuf field <code>int64 level = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLevel($var)
    {
        GPBUtil::checkInt64($var);
        $this->level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string dm_icon_key = 2;</code>
     * @return string
     */
    public function getDmIconKey()
    {
        return $this->dm_icon_key;
    }

    /**
     * Generated from protobuf field <code>string dm_icon_key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDmIconKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->dm_icon_key = $var;

        return $this;
    }

}

