<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: INTERACT_WORD_V2.proto

namespace app\Protobuf\InteractWordV2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>WealthOption</code>
 */
class WealthOption extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 roomid = 1;</code>
     */
    protected $roomid = 0;
    /**
     * Generated from protobuf field <code>int64 view_uid = 2;</code>
     */
    protected $view_uid = 0;
    /**
     * Generated from protobuf field <code>int64 ruid = 3;</code>
     */
    protected $ruid = 0;
    /**
     * Generated from protobuf field <code>bool strong_depend = 4;</code>
     */
    protected $strong_depend = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $roomid
     *     @type int|string $view_uid
     *     @type int|string $ruid
     *     @type bool $strong_depend
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\INTERACTWORDV2::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 roomid = 1;</code>
     * @return int|string
     */
    public function getRoomid()
    {
        return $this->roomid;
    }

    /**
     * Generated from protobuf field <code>int64 roomid = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRoomid($var)
    {
        GPBUtil::checkInt64($var);
        $this->roomid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 view_uid = 2;</code>
     * @return int|string
     */
    public function getViewUid()
    {
        return $this->view_uid;
    }

    /**
     * Generated from protobuf field <code>int64 view_uid = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setViewUid($var)
    {
        GPBUtil::checkInt64($var);
        $this->view_uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 ruid = 3;</code>
     * @return int|string
     */
    public function getRuid()
    {
        return $this->ruid;
    }

    /**
     * Generated from protobuf field <code>int64 ruid = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRuid($var)
    {
        GPBUtil::checkInt64($var);
        $this->ruid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool strong_depend = 4;</code>
     * @return bool
     */
    public function getStrongDepend()
    {
        return $this->strong_depend;
    }

    /**
     * Generated from protobuf field <code>bool strong_depend = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setStrongDepend($var)
    {
        GPBUtil::checkBool($var);
        $this->strong_depend = $var;

        return $this;
    }

}

