<?php

declare(strict_types=1);

use Phinx\Migration\AbstractMigration;
use Phinx\Db\Adapter\MysqlAdapter;

final class CreateMenus extends AbstractMigration
{
    /**
     * Change Method.
     *
     * Write your reversible migrations using this method.
     *
     * More information on writing migrations is available here:
     * https://book.cakephp.org/phinx/0/en/migrations.html#the-change-method
     *
     * Remember to call "create()" or "update()" and NOT "save()" when working
     * with the Table class.
     */
    public function change(): void
    {
        // 创建表
        $table = $this->table('bl_menus', ['id' => 'id', 'engine' => 'InnoDB', 'collation' => 'utf8mb4_unicode_ci', 'comment' => '菜单表']);
        // 添加字段
        $table->addColumn('code', 'string', ['null' => false, 'comment' => '编码'])
            ->addColumn('enable', 'integer', ['limit' => MysqlAdapter::INT_TINY, 'null' => false, 'default' => 0, 'comment' => '是否启用'])
            ->addColumn('show', 'integer', ['limit' => MysqlAdapter::INT_TINY, 'null' => false, 'default' => 0, 'comment' => '显示状态'])
            ->addColumn('keep_alive', 'integer', ['limit' => MysqlAdapter::INT_TINY, 'null' => false, 'default' => 0, 'comment' => '是否KeepAlive'])
            ->addColumn('layout', 'string', ['null' => false, 'default' => '', 'comment' => 'layout'])
            ->addColumn('type', 'string', ['null' => false, 'default' => '', 'comment' => '类型'])
            ->addColumn('parent_id', 'integer', ['limit' => MysqlAdapter::INT_BIG, 'null' => false, 'default' => 0, 'comment' => '父级ID'])
            ->addColumn('name', 'string', ['null' => false, 'comment' => '名称'])
            ->addColumn('icon', 'string', ['null' => false, 'comment' => '菜单图标'])
            ->addColumn('path', 'string', ['null' => false, 'comment' => '路由地址'])
            ->addColumn('component', 'string', ['null' => false, 'comment' => '组件路径'])
            ->addColumn('order', 'integer', ['limit' => MysqlAdapter::INT_MEDIUM, 'null' => false, 'comment' => '排序'])
            ->addColumn('created_at', 'integer', ['limit' => MysqlAdapter::INT_BIG, 'null' => false, 'comment' => '创建时间'])
            ->addColumn('updated_at', 'integer', ['limit' => MysqlAdapter::INT_BIG, 'null' => true, 'comment' => '更新时间'])
            ->addColumn('deleted_at', 'integer', ['limit' => MysqlAdapter::INT_BIG, 'null' => true, 'comment' => '逻辑删除'])
            ->create();
        // 预填充信息
        $rows = [
            [
                "id" => 1,
                "code" => "SysMgt",
                "icon" => "i-fe:grid",
                "name" => "系统管理",
                "path" => "",
                "show" => 1,
                "type" => "MENU",
                "order" => 98,
                "enable" => 1,
                "layout" => "",
                "component" => "",
                "parent_id" => 0,
                "keep_alive" => 0,
                'created_at' => time(),
                'updated_at' => time(),
                'deleted_at' => NULL
            ],
            [
                "id" => 2,
                "code" => "MenuMgt",
                "icon" => "i-fe:list",
                "name" => "菜单管理",
                "path" => "/pms/resource",
                "show" => 1,
                "type" => "MENU",
                "order" => 1,
                "enable" => 1,
                "layout" => "",
                "component" => "/src/views/pms/resource/index.vue",
                "parent_id" => 1,
                "keep_alive" => 0,
                'created_at' => time(),
                'updated_at' => time(),
                'deleted_at' => NULL
            ],
            [
                "id" => 3,
                "code" => "RoleMgt",
                "icon" => "i-fe:user-check",
                "name" => "角色管理",
                "path" => "/pms/role",
                "show" => 1,
                "type" => "MENU",
                "order" => 2,
                "enable" => 1,
                "layout" => "",
                "component" => "/src/views/pms/role/index.vue",
                "parent_id" => 1,
                "keep_alive" => 0,
                'created_at' => time(),
                'updated_at' => time(),
                'deleted_at' => NULL
            ],
            [
                "id" => 4,
                "code" => "UserMgt",
                "icon" => "i-fe:user",
                "name" => "用户管理",
                "path" => "/pms/user",
                "show" => 1,
                "type" => "MENU",
                "order" => 3,
                "enable" => 1,
                "layout" => "",
                "component" => "/src/views/pms/user/index.vue",
                "parent_id" => 1,
                "keep_alive" => 1,
                'created_at' => time(),
                'updated_at' => time(),
                'deleted_at' => NULL
            ],
            [
                "id" => 5,
                "code" => "RoleUser",
                "icon" => "i-fe:user-plus",
                "name" => "分配用户",
                "path" => "/pms/role/user/:roleId",
                "show" => 0,
                "type" => "MENU",
                "order" => 1,
                "enable" => 1,
                "layout" => "full",
                "component" => "/src/views/pms/role/role-user.vue",
                "parent_id" => 3,
                "keep_alive" => 0,
                'created_at' => time(),
                'updated_at' => time(),
                'deleted_at' => NULL
            ],
            [
                "id" => 6,
                "code" => "AddRole",
                "icon" => "",
                "name" => "新增角色",
                "path" => "",
                "show" => 1,
                "type" => "BUTTON",
                "order" => 0,
                "enable" => 1,
                "layout" => "",
                "component" => "",
                "parent_id" => 3,
                "keep_alive" => 0,
                'created_at' => time(),
                'updated_at' => time(),
                'deleted_at' => NULL
            ],
            [
                "id" => 7,
                "code" => "AddUser",
                "icon" => "",
                "name" => "添加用户",
                "path" => "",
                "show" => 1,
                "type" => "BUTTON",
                "order" => 0,
                "enable" => 1,
                "layout" => "",
                "component" => "",
                "parent_id" => 4,
                "keep_alive" => 0,
                'created_at' => time(),
                'updated_at' => time(),
                'deleted_at' => NULL
            ],
            [
                "id" => 8,
                "code" => "UserProfile",
                "icon" => "i-fe:user",
                "name" => "个人资料",
                "path" => "/profile",
                "show" => 0,
                "type" => "MENU",
                "order" => 99,
                "enable" => 1,
                "layout" => "",
                "component" => "/src/views/profile/index.vue",
                "parent_id" => 0,
                "keep_alive" => 0,
                'created_at' => time(),
                'updated_at' => time(),
                'deleted_at' => NULL
            ],
            [
                "id" => 9,
                "code" => "Home",
                "icon" => "i-fe:home",
                "name" => "欢迎您",
                "path" => "/",
                "show" => 1,
                "type" => "MENU",
                "order" => 0,
                "enable" => 1,
                "layout" => "",
                "component" => "/src/views/home/index.vue",
                "parent_id" => 0,
                "keep_alive" => 0,
                'created_at' => time(),
                'updated_at' => time(),
                'deleted_at' => NULL
            ],
            [
                "id" => 10,
                "code" => "iFrame",
                "icon" => "i-fe:insert-link",
                "name" => "外部链接",
                "path" => "https://hejunjie.life",
                "show" => 1,
                "type" => "MENU",
                "order" => 0,
                "enable" => 1,
                "layout" => "",
                "component" => "",
                "parent_id" => 0,
                "keep_alive" => 0,
                'created_at' => time(),
                'updated_at' => time(),
                'deleted_at' => time()
            ],
            [
                "id" => 11,
                "code" => "RobotControl",
                "icon" => "i-fe:codesandbox",
                "name" => "机器人控制",
                "path" => "/robot-control",
                "show" => 1,
                "type" => "MENU",
                "order" => 1,
                "enable" => 1,
                "layout" => "",
                "component" => "/src/views/robot-control/index.vue",
                "parent_id" => 0,
                "keep_alive" => 0,
                'created_at' => time(),
                'updated_at' => time(),
                'deleted_at' => NULL
            ],
            [
                "id" => 12,
                "code" => "Configuration",
                "icon" => "i-fe:settings",
                "name" => "配置管理",
                "path" => "",
                "show" => 1,
                "type" => "MENU",
                "order" => 2,
                "enable" => 1,
                "layout" => "",
                "component" => "",
                "parent_id" => 0,
                "keep_alive" => 0,
                'created_at' => time(),
                'updated_at' => time(),
                'deleted_at' => NULL
            ],
            [
                "id" => 13,
                "code" => "ConfigurationShopSettings",
                "icon" => "i-fe:tag",
                "name" => "商城配置",
                "path" => "/configuration/shop-settings",
                "show" => 1,
                "type" => "MENU",
                "order" => 0,
                "enable" => 1,
                "layout" => "",
                "component" => "/src/views/configuration/shop-settings/index.vue",
                "parent_id" => 12,
                "keep_alive" => 0,
                'created_at' => time(),
                'updated_at' => time(),
                'deleted_at' => NULL
            ],
            [
                "id" => 14,
                "code" => "ConfigurationSystemSettings",
                "icon" => "i-fe:tag",
                "name" => "系统配置",
                "path" => "/configuration/system-settings",
                "show" => 1,
                "type" => "MENU",
                "order" => 1,
                "enable" => 1,
                "layout" => "",
                "component" => "/src/views/configuration/system-settings/index.vue",
                "parent_id" => 12,
                "keep_alive" => 0,
                'created_at' => time(),
                'updated_at' => time(),
                'deleted_at' => NULL
            ],
            [
                "id" => 15,
                "code" => "ShopManagement",
                "icon" => "i-fe:shopping-bag",
                "name" => "商城管理",
                "path" => "",
                "show" => 1,
                "type" => "MENU",
                "order" => 3,
                "enable" => 1,
                "layout" => "",
                "component" => "",
                "parent_id" => 0,
                "keep_alive" => 0,
                'created_at' => time(),
                'updated_at' => time(),
                'deleted_at' => NULL
            ],
            [
                "id" => 16,
                "code" => "ShopManagementProductManagement",
                "icon" => "i-fe:shopping-cart",
                "name" => "商品管理",
                "path" => "/shop-sanagement/product-management",
                "show" => 1,
                "type" => "MENU",
                "order" => 0,
                "enable" => 1,
                "layout" => "",
                "component" => "/src/views/shop-management/product-management/index.vue",
                "parent_id" => 15,
                "keep_alive" => 0,
                'created_at' => time(),
                'updated_at' => time(),
                'deleted_at' => NULL
            ],
            [
                "id" => 17,
                "code" => "ShopManagementUserManagement",
                "icon" => "i-fe:users",
                "name" => "用户管理",
                "path" => "/shop-management/user-management",
                "show" => 1,
                "type" => "MENU",
                "order" => 1,
                "enable" => 1,
                "layout" => "",
                "component" => "/src/views/shop-management/user-management/index.vue",
                "parent_id" => 15,
                "keep_alive" => 0,
                'created_at' => time(),
                'updated_at' => time(),
                'deleted_at' => NULL
            ],
            [
                "id" => 18,
                "code" => "ShopManagementShippingManagement",
                "icon" => "i-fe:truck",
                "name" => "发货管理",
                "path" => "/shop-management/shipping-management",
                "show" => 1,
                "type" => "MENU",
                "order" => 2,
                "enable" => 1,
                "layout" => "",
                "component" => "/src/views/shop-management/shipping-management/index.vue",
                "parent_id" => 15,
                "keep_alive" => 0,
                'created_at' => time(),
                'updated_at' => time(),
                'deleted_at' => NULL
            ],
            [
                "id" => 19,
                "code" => "Others",
                "icon" => "i-fe:box",
                "name" => "其他",
                "path" => "",
                "show" => 1,
                "type" => "MENU",
                "order" => 4,
                "enable" => 1,
                "layout" => "",
                "component" => "",
                "parent_id" => 0,
                "keep_alive" => 0,
                'created_at' => time(),
                'updated_at' => time(),
                'deleted_at' => NULL
            ],
            [
                "id" => 20,
                "code" => "OthersDanmakuInfo",
                "icon" => "i-fe:message-circle",
                "name" => "弹幕信息",
                "path" => "/others/danmaku-info",
                "show" => 1,
                "type" => "MENU",
                "order" => 0,
                "enable" => 1,
                "layout" => "",
                "component" => "/src/views/others/danmaku-info/index.vue",
                "parent_id" => 19,
                "keep_alive" => 0,
                'created_at' => time(),
                'updated_at' => time(),
                'deleted_at' => NULL
            ],
            [
                "id" => 21,
                "code" => "OthersGiftInfo",
                "icon" => "i-fe:gift",
                "name" => "礼物信息",
                "path" => "/others/gift-info",
                "show" => 1,
                "type" => "MENU",
                "order" => 1,
                "enable" => 1,
                "layout" => "",
                "component" => "/src/views/others/gift-info/index.vue",
                "parent_id" => 19,
                "keep_alive" => 0,
                'created_at' => time(),
                'updated_at' => time(),
                'deleted_at' => NULL
            ],
            [
                "id" => 22,
                "code" => "OthersComplaintManagement",
                "icon" => "i-fe:sliders",
                "name" => "投诉管理",
                "path" => "/others/complaint-management",
                "show" => 1,
                "type" => "MENU",
                "order" => 2,
                "enable" => 1,
                "layout" => "",
                "component" => "/src/views/others/complaint-management/index.vue",
                "parent_id" => 19,
                "keep_alive" => 0,
                'created_at' => time(),
                'updated_at' => time(),
                'deleted_at' => NULL
            ],
            [
                "id" => 23,
                "code" => "OthersFeedback",
                "icon" => "i-fe:link",
                "name" => "问题反馈",
                "path" => "https://hejunjie.life",
                "show" => 1,
                "type" => "MENU",
                "order" => 3,
                "enable" => 1,
                "layout" => "",
                "component" => "",
                "parent_id" => 19,
                "keep_alive" => 0,
                'created_at' => time(),
                'updated_at' => time(),
                'deleted_at' => NULL
            ],
            [
                "id" => 24,
                "code" => "ShopManagementProductManagementAdd",
                "icon" => "",
                "name" => "新增商品",
                "path" => "",
                "show" => 1,
                "type" => "BUTTON",
                "order" => 0,
                "enable" => 1,
                "layout" => "",
                "component" => "",
                "parent_id" => 16,
                "keep_alive" => 0,
                'created_at' => time(),
                'updated_at' => time(),
                'deleted_at' => NULL
            ],
            [
                "id" => 25,
                "code" => "ShopManagementProductManagementEdit",
                "icon" => "",
                "name" => "编辑商品",
                "path" => "",
                "show" => 1,
                "type" => "BUTTON",
                "order" => 0,
                "enable" => 1,
                "layout" => "",
                "component" => "",
                "parent_id" => 16,
                "keep_alive" => 0,
                'created_at' => time(),
                'updated_at' => time(),
                'deleted_at' => NULL
            ],
            [
                "id" => 26,
                "code" => "ShopManagementUserManagementAdd",
                "icon" => "",
                "name" => "添加用户",
                "path" => "",
                "show" => 1,
                "type" => "BUTTON",
                "order" => 0,
                "enable" => 1,
                "layout" => "",
                "component" => "",
                "parent_id" => 17,
                "keep_alive" => 0,
                'created_at' => time(),
                'updated_at' => time(),
                'deleted_at' => NULL
            ],
            [
                "id" => 27,
                "code" => "ShopManagementUserManagementReset",
                "icon" => "",
                "name" => "重置全部用户密码",
                "path" => "",
                "show" => 1,
                "type" => "BUTTON",
                "order" => 0,
                "enable" => 1,
                "layout" => "",
                "component" => "",
                "parent_id" => 17,
                "keep_alive" => 0,
                'created_at' => time(),
                'updated_at' => time(),
                'deleted_at' => NULL
            ],
            [
                "id" => 28,
                "code" => "ShopManagementUserManagementEdit",
                "icon" => "",
                "name" => "变更用户信息",
                "path" => "",
                "show" => 1,
                "type" => "BUTTON",
                "order" => 0,
                "enable" => 1,
                "layout" => "",
                "component" => "",
                "parent_id" => 17,
                "keep_alive" => 0,
                'created_at' => time(),
                'updated_at' => time(),
                'deleted_at' => NULL
            ],
            [
                "id" => 29,
                "code" => "ShopManagementUserManagementEditPoint",
                "icon" => "",
                "name" => "变更用户积分",
                "path" => "",
                "show" => 1,
                "type" => "BUTTON",
                "order" => 0,
                "enable" => 1,
                "layout" => "",
                "component" => "",
                "parent_id" => 17,
                "keep_alive" => 0,
                'created_at' => time(),
                'updated_at' => time(),
                'deleted_at' => NULL
            ],
            [
                "id" => 30,
                "code" => "ShopManagementShippingManagementEdit",
                "icon" => "",
                "name" => "变更发货状态",
                "path" => "",
                "show" => 1,
                "type" => "BUTTON",
                "order" => 0,
                "enable" => 1,
                "layout" => "",
                "component" => "",
                "parent_id" => 18,
                "keep_alive" => 0,
                'created_at' => time(),
                'updated_at' => time(),
                'deleted_at' => NULL
            ],
            [
                "id" => 31,
                "code" => "ConfigurationSystemSettingsEdit",
                "icon" => "",
                "name" => "保存配置",
                "path" => "",
                "show" => 1,
                "type" => "BUTTON",
                "order" => 0,
                "enable" => 1,
                "layout" => "",
                "component" => "",
                "parent_id" => 14,
                "keep_alive" => 0,
                'created_at' => time(),
                'updated_at' => time(),
                'deleted_at' => NULL
            ],
            [
                "id" => 32,
                "code" => "ConfigurationShopSettingsEdit",
                "icon" => "",
                "name" => "保存配置",
                "path" => "",
                "show" => 1,
                "type" => "BUTTON",
                "order" => 0,
                "enable" => 1,
                "layout" => "",
                "component" => "",
                "parent_id" => 13,
                "keep_alive" => 0,
                'created_at' => time(),
                'updated_at' => time(),
                'deleted_at' => NULL
            ],
            [
                "id" => 33,
                "code" => "RobotControlUser",
                "icon" => "",
                "name" => "操作账号",
                "path" => "",
                "show" => 1,
                "type" => "BUTTON",
                "order" => 0,
                "enable" => 1,
                "layout" => "",
                "component" => "",
                "parent_id" => 11,
                "keep_alive" => 0,
                'created_at' => time(),
                'updated_at' => time(),
                'deleted_at' => NULL
            ],
            [
                "id" => 34,
                "code" => "RobotControlRoom",
                "icon" => "",
                "name" => "操作直播间",
                "path" => "",
                "show" => 1,
                "type" => "BUTTON",
                "order" => 0,
                "enable" => 1,
                "layout" => "",
                "component" => "",
                "parent_id" => 11,
                "keep_alive" => 0,
                'created_at' => time(),
                'updated_at' => time(),
                'deleted_at' => NULL
            ],
            [
                "id" => 35,
                "code" => "RobotControlEdit",
                "icon" => "",
                "name" => "保存配置",
                "path" => "",
                "show" => 1,
                "type" => "BUTTON",
                "order" => 0,
                "enable" => 1,
                "layout" => "",
                "component" => "",
                "parent_id" => 11,
                "keep_alive" => 0,
                'created_at' => time(),
                'updated_at' => time(),
                'deleted_at' => NULL
            ]
        ];
        $table->insert($rows)->saveData();
    }
}
