<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SEND_GIFT_V2.proto

namespace app\Protobuf\SendGiftV2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 10.31
 *
 * Generated from protobuf message <code>BagGiftInfo</code>
 */
class BagGiftInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 show_price = 1;</code>
     */
    protected $show_price = 0;
    /**
     * Generated from protobuf field <code>int64 price_for_show = 2;</code>
     */
    protected $price_for_show = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $show_price
     *     @type int|string $price_for_show
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SENDGIFTV2::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 show_price = 1;</code>
     * @return int
     */
    public function getShowPrice()
    {
        return $this->show_price;
    }

    /**
     * Generated from protobuf field <code>int32 show_price = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setShowPrice($var)
    {
        GPBUtil::checkInt32($var);
        $this->show_price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 price_for_show = 2;</code>
     * @return int|string
     */
    public function getPriceForShow()
    {
        return $this->price_for_show;
    }

    /**
     * Generated from protobuf field <code>int64 price_for_show = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPriceForShow($var)
    {
        GPBUtil::checkInt64($var);
        $this->price_for_show = $var;

        return $this;
    }

}

