<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SEND_GIFT_V2.proto

namespace app\Protobuf\SendGiftV2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 9
 *
 * Generated from protobuf message <code>BlindGift</code>
 */
class BlindGift extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 blind_gift_config_id = 1;</code>
     */
    protected $blind_gift_config_id = 0;
    /**
     * Generated from protobuf field <code>int64 original_gift_id = 2;</code>
     */
    protected $original_gift_id = 0;
    /**
     * Generated from protobuf field <code>string original_gift_name = 3;</code>
     */
    protected $original_gift_name = '';
    /**
     * Generated from protobuf field <code>int64 from = 4;</code>
     */
    protected $from = 0;
    /**
     * Generated from protobuf field <code>string gift_action = 5;</code>
     */
    protected $gift_action = '';
    /**
     * Generated from protobuf field <code>int64 original_gift_price = 6;</code>
     */
    protected $original_gift_price = 0;
    /**
     * Generated from protobuf field <code>int64 gift_tip_price = 7;</code>
     */
    protected $gift_tip_price = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $blind_gift_config_id
     *     @type int|string $original_gift_id
     *     @type string $original_gift_name
     *     @type int|string $from
     *     @type string $gift_action
     *     @type int|string $original_gift_price
     *     @type int|string $gift_tip_price
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SENDGIFTV2::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 blind_gift_config_id = 1;</code>
     * @return int|string
     */
    public function getBlindGiftConfigId()
    {
        return $this->blind_gift_config_id;
    }

    /**
     * Generated from protobuf field <code>int64 blind_gift_config_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBlindGiftConfigId($var)
    {
        GPBUtil::checkInt64($var);
        $this->blind_gift_config_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 original_gift_id = 2;</code>
     * @return int|string
     */
    public function getOriginalGiftId()
    {
        return $this->original_gift_id;
    }

    /**
     * Generated from protobuf field <code>int64 original_gift_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOriginalGiftId($var)
    {
        GPBUtil::checkInt64($var);
        $this->original_gift_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string original_gift_name = 3;</code>
     * @return string
     */
    public function getOriginalGiftName()
    {
        return $this->original_gift_name;
    }

    /**
     * Generated from protobuf field <code>string original_gift_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setOriginalGiftName($var)
    {
        GPBUtil::checkString($var, True);
        $this->original_gift_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 from = 4;</code>
     * @return int|string
     */
    public function getFrom()
    {
        return $this->from;
    }

    /**
     * Generated from protobuf field <code>int64 from = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFrom($var)
    {
        GPBUtil::checkInt64($var);
        $this->from = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string gift_action = 5;</code>
     * @return string
     */
    public function getGiftAction()
    {
        return $this->gift_action;
    }

    /**
     * Generated from protobuf field <code>string gift_action = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setGiftAction($var)
    {
        GPBUtil::checkString($var, True);
        $this->gift_action = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 original_gift_price = 6;</code>
     * @return int|string
     */
    public function getOriginalGiftPrice()
    {
        return $this->original_gift_price;
    }

    /**
     * Generated from protobuf field <code>int64 original_gift_price = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOriginalGiftPrice($var)
    {
        GPBUtil::checkInt64($var);
        $this->original_gift_price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 gift_tip_price = 7;</code>
     * @return int|string
     */
    public function getGiftTipPrice()
    {
        return $this->gift_tip_price;
    }

    /**
     * Generated from protobuf field <code>int64 gift_tip_price = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setGiftTipPrice($var)
    {
        GPBUtil::checkInt64($var);
        $this->gift_tip_price = $var;

        return $this;
    }

}

