<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SEND_GIFT_V2.proto

namespace app\Protobuf\SendGiftV2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GiftItem</code>
 */
class GiftItem extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 gift_id = 1;</code>
     */
    protected $gift_id = 0;
    /**
     * Generated from protobuf field <code>string gift_name = 2;</code>
     */
    protected $gift_name = '';
    /**
     * Generated from protobuf field <code>int64 num = 3;</code>
     */
    protected $num = 0;
    /**
     * Generated from protobuf field <code>int64 demarcation = 4;</code>
     */
    protected $demarcation = 0;
    /**
     * Generated from protobuf field <code>int64 price = 5;</code>
     */
    protected $price = 0;
    /**
     * Generated from protobuf field <code>int64 discount_price = 6;</code>
     */
    protected $discount_price = 0;
    /**
     * Generated from protobuf field <code>int64 total_coin = 7;</code>
     */
    protected $total_coin = 0;
    /**
     * Generated from protobuf field <code>string coin_type = 8;</code>
     */
    protected $coin_type = '';
    /**
     * Generated from protobuf field <code>string tid = 9;</code>
     */
    protected $tid = '';
    /**
     * Generated from protobuf field <code>int64 timestamp = 10;</code>
     */
    protected $timestamp = 0;
    /**
     * Generated from protobuf field <code>int64 super_batch_gift_num = 11;</code>
     */
    protected $super_batch_gift_num = 0;
    /**
     * Generated from protobuf field <code>string batch_combo_id = 12;</code>
     */
    protected $batch_combo_id = '';
    /**
     * Generated from protobuf field <code>int64 combo_resources_id = 13;</code>
     */
    protected $combo_resources_id = 0;
    /**
     * Generated from protobuf field <code>int64 combo_total_coin = 14;</code>
     */
    protected $combo_total_coin = 0;
    /**
     * Generated from protobuf field <code>int64 combo_stay_time = 15;</code>
     */
    protected $combo_stay_time = 0;
    /**
     * Generated from protobuf field <code>float magnification = 16;</code>
     */
    protected $magnification = 0.0;
    /**
     * Generated from protobuf field <code>bool show_batch_combo_send = 17;</code>
     */
    protected $show_batch_combo_send = false;
    /**
     * Generated from protobuf field <code>string action = 18;</code>
     */
    protected $action = '';
    /**
     * Generated from protobuf field <code>int64 effect_block = 19;</code>
     */
    protected $effect_block = 0;
    /**
     * Generated from protobuf field <code>int64 is_special_batch = 20;</code>
     */
    protected $is_special_batch = 0;
    /**
     * Generated from protobuf field <code>int64 float_sc_resource_id = 21;</code>
     */
    protected $float_sc_resource_id = 0;
    /**
     * Generated from protobuf field <code>string tag_image = 22;</code>
     */
    protected $tag_image = '';
    /**
     * Generated from protobuf field <code>int64 crit_prob = 23;</code>
     */
    protected $crit_prob = 0;
    /**
     * Generated from protobuf field <code>int64 rcost = 24;</code>
     */
    protected $rcost = 0;
    /**
     * Generated from protobuf field <code>int64 test = 25;</code>
     */
    protected $test = 0;
    /**
     * Generated from protobuf field <code>int64 face_effect_type = 26;</code>
     */
    protected $face_effect_type = 0;
    /**
     * Generated from protobuf field <code>int64 face_effect_id = 27;</code>
     */
    protected $face_effect_id = 0;
    /**
     * Generated from protobuf field <code>bool is_naming = 28;</code>
     */
    protected $is_naming = false;
    /**
     * Generated from protobuf field <code>.ReceiveUserInfo receive_user_info = 29;</code>
     */
    protected $receive_user_info = null;
    /**
     * Generated from protobuf field <code>bool is_join_receiver = 30;</code>
     */
    protected $is_join_receiver = false;
    /**
     * Generated from protobuf field <code>.BagGiftInfo bag_gift = 31;</code>
     */
    protected $bag_gift = null;
    /**
     * Generated from protobuf field <code>repeated int64 gift_tag = 32;</code>
     */
    private $gift_tag;
    /**
     * Generated from protobuf field <code>.UserInfo receiver_uinfo = 33;</code>
     */
    protected $receiver_uinfo = null;
    /**
     * Generated from protobuf field <code>.FaceEffectV2 face_effect_v2 = 34;</code>
     */
    protected $face_effect_v2 = null;
    /**
     * Generated from protobuf field <code>.GiftMaterialSnapShot gift_info = 35;</code>
     */
    protected $gift_info = null;
    /**
     * Generated from protobuf field <code>int64 gift_tip_price = 36;</code>
     */
    protected $gift_tip_price = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $gift_id
     *     @type string $gift_name
     *     @type int|string $num
     *     @type int|string $demarcation
     *     @type int|string $price
     *     @type int|string $discount_price
     *     @type int|string $total_coin
     *     @type string $coin_type
     *     @type string $tid
     *     @type int|string $timestamp
     *     @type int|string $super_batch_gift_num
     *     @type string $batch_combo_id
     *     @type int|string $combo_resources_id
     *     @type int|string $combo_total_coin
     *     @type int|string $combo_stay_time
     *     @type float $magnification
     *     @type bool $show_batch_combo_send
     *     @type string $action
     *     @type int|string $effect_block
     *     @type int|string $is_special_batch
     *     @type int|string $float_sc_resource_id
     *     @type string $tag_image
     *     @type int|string $crit_prob
     *     @type int|string $rcost
     *     @type int|string $test
     *     @type int|string $face_effect_type
     *     @type int|string $face_effect_id
     *     @type bool $is_naming
     *     @type \app\Protobuf\SendGiftV2\ReceiveUserInfo $receive_user_info
     *     @type bool $is_join_receiver
     *     @type \app\Protobuf\SendGiftV2\BagGiftInfo $bag_gift
     *     @type array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $gift_tag
     *     @type \app\Protobuf\SendGiftV2\UserInfo $receiver_uinfo
     *     @type \app\Protobuf\SendGiftV2\FaceEffectV2 $face_effect_v2
     *     @type \app\Protobuf\SendGiftV2\GiftMaterialSnapShot $gift_info
     *     @type int|string $gift_tip_price
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SENDGIFTV2::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 gift_id = 1;</code>
     * @return int|string
     */
    public function getGiftId()
    {
        return $this->gift_id;
    }

    /**
     * Generated from protobuf field <code>int64 gift_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setGiftId($var)
    {
        GPBUtil::checkInt64($var);
        $this->gift_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string gift_name = 2;</code>
     * @return string
     */
    public function getGiftName()
    {
        return $this->gift_name;
    }

    /**
     * Generated from protobuf field <code>string gift_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setGiftName($var)
    {
        GPBUtil::checkString($var, True);
        $this->gift_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 num = 3;</code>
     * @return int|string
     */
    public function getNum()
    {
        return $this->num;
    }

    /**
     * Generated from protobuf field <code>int64 num = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNum($var)
    {
        GPBUtil::checkInt64($var);
        $this->num = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 demarcation = 4;</code>
     * @return int|string
     */
    public function getDemarcation()
    {
        return $this->demarcation;
    }

    /**
     * Generated from protobuf field <code>int64 demarcation = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDemarcation($var)
    {
        GPBUtil::checkInt64($var);
        $this->demarcation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 price = 5;</code>
     * @return int|string
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Generated from protobuf field <code>int64 price = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkInt64($var);
        $this->price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 discount_price = 6;</code>
     * @return int|string
     */
    public function getDiscountPrice()
    {
        return $this->discount_price;
    }

    /**
     * Generated from protobuf field <code>int64 discount_price = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDiscountPrice($var)
    {
        GPBUtil::checkInt64($var);
        $this->discount_price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 total_coin = 7;</code>
     * @return int|string
     */
    public function getTotalCoin()
    {
        return $this->total_coin;
    }

    /**
     * Generated from protobuf field <code>int64 total_coin = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalCoin($var)
    {
        GPBUtil::checkInt64($var);
        $this->total_coin = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string coin_type = 8;</code>
     * @return string
     */
    public function getCoinType()
    {
        return $this->coin_type;
    }

    /**
     * Generated from protobuf field <code>string coin_type = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setCoinType($var)
    {
        GPBUtil::checkString($var, True);
        $this->coin_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string tid = 9;</code>
     * @return string
     */
    public function getTid()
    {
        return $this->tid;
    }

    /**
     * Generated from protobuf field <code>string tid = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setTid($var)
    {
        GPBUtil::checkString($var, True);
        $this->tid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 10;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 super_batch_gift_num = 11;</code>
     * @return int|string
     */
    public function getSuperBatchGiftNum()
    {
        return $this->super_batch_gift_num;
    }

    /**
     * Generated from protobuf field <code>int64 super_batch_gift_num = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSuperBatchGiftNum($var)
    {
        GPBUtil::checkInt64($var);
        $this->super_batch_gift_num = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string batch_combo_id = 12;</code>
     * @return string
     */
    public function getBatchComboId()
    {
        return $this->batch_combo_id;
    }

    /**
     * Generated from protobuf field <code>string batch_combo_id = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setBatchComboId($var)
    {
        GPBUtil::checkString($var, True);
        $this->batch_combo_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 combo_resources_id = 13;</code>
     * @return int|string
     */
    public function getComboResourcesId()
    {
        return $this->combo_resources_id;
    }

    /**
     * Generated from protobuf field <code>int64 combo_resources_id = 13;</code>
     * @param int|string $var
     * @return $this
     */
    public function setComboResourcesId($var)
    {
        GPBUtil::checkInt64($var);
        $this->combo_resources_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 combo_total_coin = 14;</code>
     * @return int|string
     */
    public function getComboTotalCoin()
    {
        return $this->combo_total_coin;
    }

    /**
     * Generated from protobuf field <code>int64 combo_total_coin = 14;</code>
     * @param int|string $var
     * @return $this
     */
    public function setComboTotalCoin($var)
    {
        GPBUtil::checkInt64($var);
        $this->combo_total_coin = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 combo_stay_time = 15;</code>
     * @return int|string
     */
    public function getComboStayTime()
    {
        return $this->combo_stay_time;
    }

    /**
     * Generated from protobuf field <code>int64 combo_stay_time = 15;</code>
     * @param int|string $var
     * @return $this
     */
    public function setComboStayTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->combo_stay_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float magnification = 16;</code>
     * @return float
     */
    public function getMagnification()
    {
        return $this->magnification;
    }

    /**
     * Generated from protobuf field <code>float magnification = 16;</code>
     * @param float $var
     * @return $this
     */
    public function setMagnification($var)
    {
        GPBUtil::checkFloat($var);
        $this->magnification = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool show_batch_combo_send = 17;</code>
     * @return bool
     */
    public function getShowBatchComboSend()
    {
        return $this->show_batch_combo_send;
    }

    /**
     * Generated from protobuf field <code>bool show_batch_combo_send = 17;</code>
     * @param bool $var
     * @return $this
     */
    public function setShowBatchComboSend($var)
    {
        GPBUtil::checkBool($var);
        $this->show_batch_combo_send = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string action = 18;</code>
     * @return string
     */
    public function getAction()
    {
        return $this->action;
    }

    /**
     * Generated from protobuf field <code>string action = 18;</code>
     * @param string $var
     * @return $this
     */
    public function setAction($var)
    {
        GPBUtil::checkString($var, True);
        $this->action = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 effect_block = 19;</code>
     * @return int|string
     */
    public function getEffectBlock()
    {
        return $this->effect_block;
    }

    /**
     * Generated from protobuf field <code>int64 effect_block = 19;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEffectBlock($var)
    {
        GPBUtil::checkInt64($var);
        $this->effect_block = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 is_special_batch = 20;</code>
     * @return int|string
     */
    public function getIsSpecialBatch()
    {
        return $this->is_special_batch;
    }

    /**
     * Generated from protobuf field <code>int64 is_special_batch = 20;</code>
     * @param int|string $var
     * @return $this
     */
    public function setIsSpecialBatch($var)
    {
        GPBUtil::checkInt64($var);
        $this->is_special_batch = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 float_sc_resource_id = 21;</code>
     * @return int|string
     */
    public function getFloatScResourceId()
    {
        return $this->float_sc_resource_id;
    }

    /**
     * Generated from protobuf field <code>int64 float_sc_resource_id = 21;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFloatScResourceId($var)
    {
        GPBUtil::checkInt64($var);
        $this->float_sc_resource_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string tag_image = 22;</code>
     * @return string
     */
    public function getTagImage()
    {
        return $this->tag_image;
    }

    /**
     * Generated from protobuf field <code>string tag_image = 22;</code>
     * @param string $var
     * @return $this
     */
    public function setTagImage($var)
    {
        GPBUtil::checkString($var, True);
        $this->tag_image = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 crit_prob = 23;</code>
     * @return int|string
     */
    public function getCritProb()
    {
        return $this->crit_prob;
    }

    /**
     * Generated from protobuf field <code>int64 crit_prob = 23;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCritProb($var)
    {
        GPBUtil::checkInt64($var);
        $this->crit_prob = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 rcost = 24;</code>
     * @return int|string
     */
    public function getRcost()
    {
        return $this->rcost;
    }

    /**
     * Generated from protobuf field <code>int64 rcost = 24;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRcost($var)
    {
        GPBUtil::checkInt64($var);
        $this->rcost = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 test = 25;</code>
     * @return int|string
     */
    public function getTest()
    {
        return $this->test;
    }

    /**
     * Generated from protobuf field <code>int64 test = 25;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTest($var)
    {
        GPBUtil::checkInt64($var);
        $this->test = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 face_effect_type = 26;</code>
     * @return int|string
     */
    public function getFaceEffectType()
    {
        return $this->face_effect_type;
    }

    /**
     * Generated from protobuf field <code>int64 face_effect_type = 26;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFaceEffectType($var)
    {
        GPBUtil::checkInt64($var);
        $this->face_effect_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 face_effect_id = 27;</code>
     * @return int|string
     */
    public function getFaceEffectId()
    {
        return $this->face_effect_id;
    }

    /**
     * Generated from protobuf field <code>int64 face_effect_id = 27;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFaceEffectId($var)
    {
        GPBUtil::checkInt64($var);
        $this->face_effect_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_naming = 28;</code>
     * @return bool
     */
    public function getIsNaming()
    {
        return $this->is_naming;
    }

    /**
     * Generated from protobuf field <code>bool is_naming = 28;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsNaming($var)
    {
        GPBUtil::checkBool($var);
        $this->is_naming = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.ReceiveUserInfo receive_user_info = 29;</code>
     * @return \app\Protobuf\SendGiftV2\ReceiveUserInfo|null
     */
    public function getReceiveUserInfo()
    {
        return $this->receive_user_info;
    }

    public function hasReceiveUserInfo()
    {
        return isset($this->receive_user_info);
    }

    public function clearReceiveUserInfo()
    {
        unset($this->receive_user_info);
    }

    /**
     * Generated from protobuf field <code>.ReceiveUserInfo receive_user_info = 29;</code>
     * @param \app\Protobuf\SendGiftV2\ReceiveUserInfo $var
     * @return $this
     */
    public function setReceiveUserInfo($var)
    {
        GPBUtil::checkMessage($var, \app\Protobuf\SendGiftV2\ReceiveUserInfo::class);
        $this->receive_user_info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_join_receiver = 30;</code>
     * @return bool
     */
    public function getIsJoinReceiver()
    {
        return $this->is_join_receiver;
    }

    /**
     * Generated from protobuf field <code>bool is_join_receiver = 30;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsJoinReceiver($var)
    {
        GPBUtil::checkBool($var);
        $this->is_join_receiver = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.BagGiftInfo bag_gift = 31;</code>
     * @return \app\Protobuf\SendGiftV2\BagGiftInfo|null
     */
    public function getBagGift()
    {
        return $this->bag_gift;
    }

    public function hasBagGift()
    {
        return isset($this->bag_gift);
    }

    public function clearBagGift()
    {
        unset($this->bag_gift);
    }

    /**
     * Generated from protobuf field <code>.BagGiftInfo bag_gift = 31;</code>
     * @param \app\Protobuf\SendGiftV2\BagGiftInfo $var
     * @return $this
     */
    public function setBagGift($var)
    {
        GPBUtil::checkMessage($var, \app\Protobuf\SendGiftV2\BagGiftInfo::class);
        $this->bag_gift = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int64 gift_tag = 32;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGiftTag()
    {
        return $this->gift_tag;
    }

    /**
     * Generated from protobuf field <code>repeated int64 gift_tag = 32;</code>
     * @param array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGiftTag($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->gift_tag = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.UserInfo receiver_uinfo = 33;</code>
     * @return \app\Protobuf\SendGiftV2\UserInfo|null
     */
    public function getReceiverUinfo()
    {
        return $this->receiver_uinfo;
    }

    public function hasReceiverUinfo()
    {
        return isset($this->receiver_uinfo);
    }

    public function clearReceiverUinfo()
    {
        unset($this->receiver_uinfo);
    }

    /**
     * Generated from protobuf field <code>.UserInfo receiver_uinfo = 33;</code>
     * @param \app\Protobuf\SendGiftV2\UserInfo $var
     * @return $this
     */
    public function setReceiverUinfo($var)
    {
        GPBUtil::checkMessage($var, \app\Protobuf\SendGiftV2\UserInfo::class);
        $this->receiver_uinfo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.FaceEffectV2 face_effect_v2 = 34;</code>
     * @return \app\Protobuf\SendGiftV2\FaceEffectV2|null
     */
    public function getFaceEffectV2()
    {
        return $this->face_effect_v2;
    }

    public function hasFaceEffectV2()
    {
        return isset($this->face_effect_v2);
    }

    public function clearFaceEffectV2()
    {
        unset($this->face_effect_v2);
    }

    /**
     * Generated from protobuf field <code>.FaceEffectV2 face_effect_v2 = 34;</code>
     * @param \app\Protobuf\SendGiftV2\FaceEffectV2 $var
     * @return $this
     */
    public function setFaceEffectV2($var)
    {
        GPBUtil::checkMessage($var, \app\Protobuf\SendGiftV2\FaceEffectV2::class);
        $this->face_effect_v2 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.GiftMaterialSnapShot gift_info = 35;</code>
     * @return \app\Protobuf\SendGiftV2\GiftMaterialSnapShot|null
     */
    public function getGiftInfo()
    {
        return $this->gift_info;
    }

    public function hasGiftInfo()
    {
        return isset($this->gift_info);
    }

    public function clearGiftInfo()
    {
        unset($this->gift_info);
    }

    /**
     * Generated from protobuf field <code>.GiftMaterialSnapShot gift_info = 35;</code>
     * @param \app\Protobuf\SendGiftV2\GiftMaterialSnapShot $var
     * @return $this
     */
    public function setGiftInfo($var)
    {
        GPBUtil::checkMessage($var, \app\Protobuf\SendGiftV2\GiftMaterialSnapShot::class);
        $this->gift_info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 gift_tip_price = 36;</code>
     * @return int|string
     */
    public function getGiftTipPrice()
    {
        return $this->gift_tip_price;
    }

    /**
     * Generated from protobuf field <code>int64 gift_tip_price = 36;</code>
     * @param int|string $var
     * @return $this
     */
    public function setGiftTipPrice($var)
    {
        GPBUtil::checkInt64($var);
        $this->gift_tip_price = $var;

        return $this;
    }

}

