<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SEND_GIFT_V2.proto

namespace app\Protobuf\SendGiftV2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 10.35
 *
 * Generated from protobuf message <code>GiftMaterialSnapShot</code>
 */
class GiftMaterialSnapShot extends \Google\Protobuf\Internal\Message
{
    /**
     * JS:GiftMaterialSnapShot, JAVA:BroadCastGiftInfo
     *
     * Generated from protobuf field <code>string img_basic = 1;</code>
     */
    protected $img_basic = '';
    /**
     * Generated from protobuf field <code>string webp = 2;</code>
     */
    protected $webp = '';
    /**
     * Generated from protobuf field <code>int64 effect_id = 3;</code>
     */
    protected $effect_id = 0;
    /**
     * Generated from protobuf field <code>int64 has_imaged_gift = 4;</code>
     */
    protected $has_imaged_gift = 0;
    /**
     *!
     *
     * Generated from protobuf field <code>string img_gif = 5;</code>
     */
    protected $img_gif = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $img_basic
     *           JS:GiftMaterialSnapShot, JAVA:BroadCastGiftInfo
     *     @type string $webp
     *     @type int|string $effect_id
     *     @type int|string $has_imaged_gift
     *     @type string $img_gif
     *          !
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SENDGIFTV2::initOnce();
        parent::__construct($data);
    }

    /**
     * JS:GiftMaterialSnapShot, JAVA:BroadCastGiftInfo
     *
     * Generated from protobuf field <code>string img_basic = 1;</code>
     * @return string
     */
    public function getImgBasic()
    {
        return $this->img_basic;
    }

    /**
     * JS:GiftMaterialSnapShot, JAVA:BroadCastGiftInfo
     *
     * Generated from protobuf field <code>string img_basic = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setImgBasic($var)
    {
        GPBUtil::checkString($var, True);
        $this->img_basic = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string webp = 2;</code>
     * @return string
     */
    public function getWebp()
    {
        return $this->webp;
    }

    /**
     * Generated from protobuf field <code>string webp = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setWebp($var)
    {
        GPBUtil::checkString($var, True);
        $this->webp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 effect_id = 3;</code>
     * @return int|string
     */
    public function getEffectId()
    {
        return $this->effect_id;
    }

    /**
     * Generated from protobuf field <code>int64 effect_id = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEffectId($var)
    {
        GPBUtil::checkInt64($var);
        $this->effect_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 has_imaged_gift = 4;</code>
     * @return int|string
     */
    public function getHasImagedGift()
    {
        return $this->has_imaged_gift;
    }

    /**
     * Generated from protobuf field <code>int64 has_imaged_gift = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setHasImagedGift($var)
    {
        GPBUtil::checkInt64($var);
        $this->has_imaged_gift = $var;

        return $this;
    }

    /**
     *!
     *
     * Generated from protobuf field <code>string img_gif = 5;</code>
     * @return string
     */
    public function getImgGif()
    {
        return $this->img_gif;
    }

    /**
     *!
     *
     * Generated from protobuf field <code>string img_gif = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setImgGif($var)
    {
        GPBUtil::checkString($var, True);
        $this->img_gif = $var;

        return $this;
    }

}

