<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SEND_GIFT_V2.proto

namespace app\Protobuf\SendGiftV2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 10.29
 *
 * Generated from protobuf message <code>ReceiveUserInfo</code>
 */
class ReceiveUserInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string uname = 1;</code>
     */
    protected $uname = '';
    /**
     * Generated from protobuf field <code>int64 uid = 2;</code>
     */
    protected $uid = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $uname
     *     @type int|string $uid
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SENDGIFTV2::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string uname = 1;</code>
     * @return string
     */
    public function getUname()
    {
        return $this->uname;
    }

    /**
     * Generated from protobuf field <code>string uname = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUname($var)
    {
        GPBUtil::checkString($var, True);
        $this->uname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 uid = 2;</code>
     * @return int|string
     */
    public function getUid()
    {
        return $this->uid;
    }

    /**
     * Generated from protobuf field <code>int64 uid = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUid($var)
    {
        GPBUtil::checkInt64($var);
        $this->uid = $var;

        return $this;
    }

}

