<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SEND_GIFT_V2.proto

namespace app\Protobuf\SendGiftV2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>SendGiftV2</code>
 */
class SendGiftV2 extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 uid = 1;</code>
     */
    protected $uid = 0;
    /**
     * Generated from protobuf field <code>string uname = 2;</code>
     */
    protected $uname = '';
    /**
     * Generated from protobuf field <code>string face = 3;</code>
     */
    protected $face = '';
    /**
     * Generated from protobuf field <code>string name_color = 4;</code>
     */
    protected $name_color = '';
    /**
     * Generated from protobuf field <code>int64 guard_level = 5;</code>
     */
    protected $guard_level = 0;
    /**
     * Generated from protobuf field <code>int64 svga_block = 6;</code>
     */
    protected $svga_block = 0;
    /**
     * Generated from protobuf field <code>.SendMaster send_master = 7;</code>
     */
    protected $send_master = null;
    /**
     * Generated from protobuf field <code>.MedalInfo medal_info = 8;</code>
     */
    protected $medal_info = null;
    /**
     * Generated from protobuf field <code>.BlindGift blind_gift = 9;</code>
     */
    protected $blind_gift = null;
    /**
     * Generated from protobuf field <code>.GiftItem gift_list = 10;</code>
     */
    protected $gift_list = null;
    /**
     * Generated from protobuf field <code>bool switch = 11;</code>
     */
    protected $switch = false;
    /**
     * Generated from protobuf field <code>int64 test = 12;</code>
     */
    protected $test = 0;
    /**
     * Generated from protobuf field <code>.WealthInfo wealth_info = 13;</code>
     */
    protected $wealth_info = null;
    /**
     * Generated from protobuf field <code>.GroupMedalBrief group_medal = 14;</code>
     */
    protected $group_medal = null;
    /**
     * bytes    unknown16 = 16;
     * bytes    unknown17 = 17;
     * bytes    unknown18 = 18;
     * bytes    unknown19 = 19;
     * bytes    unknown20 = 20;
     * bytes    unknown21 = 21;
     * bytes    unknown22 = 22;
     * bytes    unknown23 = 23;
     * bytes    unknown24 = 24;
     * bytes    unknown25 = 25;
     * bytes    unknown26 = 26;
     * bytes    unknown27 = 27;
     * bytes    unknown28 = 28;
     * bytes    unknown29 = 29;
     * bytes    unknown30 = 30;
     * bytes    unknown31 = 31;
     * bytes    unknown32 = 32;
     *
     * Generated from protobuf field <code>.UserInfo sender_uinfo = 15;</code>
     */
    protected $sender_uinfo = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $uid
     *     @type string $uname
     *     @type string $face
     *     @type string $name_color
     *     @type int|string $guard_level
     *     @type int|string $svga_block
     *     @type \app\Protobuf\SendGiftV2\SendMaster $send_master
     *     @type \app\Protobuf\SendGiftV2\MedalInfo $medal_info
     *     @type \app\Protobuf\SendGiftV2\BlindGift $blind_gift
     *     @type \app\Protobuf\SendGiftV2\GiftItem $gift_list
     *     @type bool $switch
     *     @type int|string $test
     *     @type \app\Protobuf\SendGiftV2\WealthInfo $wealth_info
     *     @type \app\Protobuf\SendGiftV2\GroupMedalBrief $group_medal
     *     @type \app\Protobuf\SendGiftV2\UserInfo $sender_uinfo
     *           bytes    unknown16 = 16;
     *           bytes    unknown17 = 17;
     *           bytes    unknown18 = 18;
     *           bytes    unknown19 = 19;
     *           bytes    unknown20 = 20;
     *           bytes    unknown21 = 21;
     *           bytes    unknown22 = 22;
     *           bytes    unknown23 = 23;
     *           bytes    unknown24 = 24;
     *           bytes    unknown25 = 25;
     *           bytes    unknown26 = 26;
     *           bytes    unknown27 = 27;
     *           bytes    unknown28 = 28;
     *           bytes    unknown29 = 29;
     *           bytes    unknown30 = 30;
     *           bytes    unknown31 = 31;
     *           bytes    unknown32 = 32;
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SENDGIFTV2::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 uid = 1;</code>
     * @return int|string
     */
    public function getUid()
    {
        return $this->uid;
    }

    /**
     * Generated from protobuf field <code>int64 uid = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUid($var)
    {
        GPBUtil::checkInt64($var);
        $this->uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string uname = 2;</code>
     * @return string
     */
    public function getUname()
    {
        return $this->uname;
    }

    /**
     * Generated from protobuf field <code>string uname = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUname($var)
    {
        GPBUtil::checkString($var, True);
        $this->uname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string face = 3;</code>
     * @return string
     */
    public function getFace()
    {
        return $this->face;
    }

    /**
     * Generated from protobuf field <code>string face = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setFace($var)
    {
        GPBUtil::checkString($var, True);
        $this->face = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name_color = 4;</code>
     * @return string
     */
    public function getNameColor()
    {
        return $this->name_color;
    }

    /**
     * Generated from protobuf field <code>string name_color = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setNameColor($var)
    {
        GPBUtil::checkString($var, True);
        $this->name_color = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 guard_level = 5;</code>
     * @return int|string
     */
    public function getGuardLevel()
    {
        return $this->guard_level;
    }

    /**
     * Generated from protobuf field <code>int64 guard_level = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setGuardLevel($var)
    {
        GPBUtil::checkInt64($var);
        $this->guard_level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 svga_block = 6;</code>
     * @return int|string
     */
    public function getSvgaBlock()
    {
        return $this->svga_block;
    }

    /**
     * Generated from protobuf field <code>int64 svga_block = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSvgaBlock($var)
    {
        GPBUtil::checkInt64($var);
        $this->svga_block = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.SendMaster send_master = 7;</code>
     * @return \app\Protobuf\SendGiftV2\SendMaster|null
     */
    public function getSendMaster()
    {
        return $this->send_master;
    }

    public function hasSendMaster()
    {
        return isset($this->send_master);
    }

    public function clearSendMaster()
    {
        unset($this->send_master);
    }

    /**
     * Generated from protobuf field <code>.SendMaster send_master = 7;</code>
     * @param \app\Protobuf\SendGiftV2\SendMaster $var
     * @return $this
     */
    public function setSendMaster($var)
    {
        GPBUtil::checkMessage($var, \app\Protobuf\SendGiftV2\SendMaster::class);
        $this->send_master = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.MedalInfo medal_info = 8;</code>
     * @return \app\Protobuf\SendGiftV2\MedalInfo|null
     */
    public function getMedalInfo()
    {
        return $this->medal_info;
    }

    public function hasMedalInfo()
    {
        return isset($this->medal_info);
    }

    public function clearMedalInfo()
    {
        unset($this->medal_info);
    }

    /**
     * Generated from protobuf field <code>.MedalInfo medal_info = 8;</code>
     * @param \app\Protobuf\SendGiftV2\MedalInfo $var
     * @return $this
     */
    public function setMedalInfo($var)
    {
        GPBUtil::checkMessage($var, \app\Protobuf\SendGiftV2\MedalInfo::class);
        $this->medal_info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.BlindGift blind_gift = 9;</code>
     * @return \app\Protobuf\SendGiftV2\BlindGift|null
     */
    public function getBlindGift()
    {
        return $this->blind_gift;
    }

    public function hasBlindGift()
    {
        return isset($this->blind_gift);
    }

    public function clearBlindGift()
    {
        unset($this->blind_gift);
    }

    /**
     * Generated from protobuf field <code>.BlindGift blind_gift = 9;</code>
     * @param \app\Protobuf\SendGiftV2\BlindGift $var
     * @return $this
     */
    public function setBlindGift($var)
    {
        GPBUtil::checkMessage($var, \app\Protobuf\SendGiftV2\BlindGift::class);
        $this->blind_gift = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.GiftItem gift_list = 10;</code>
     * @return \app\Protobuf\SendGiftV2\GiftItem|null
     */
    public function getGiftList()
    {
        return $this->gift_list;
    }

    public function hasGiftList()
    {
        return isset($this->gift_list);
    }

    public function clearGiftList()
    {
        unset($this->gift_list);
    }

    /**
     * Generated from protobuf field <code>.GiftItem gift_list = 10;</code>
     * @param \app\Protobuf\SendGiftV2\GiftItem $var
     * @return $this
     */
    public function setGiftList($var)
    {
        GPBUtil::checkMessage($var, \app\Protobuf\SendGiftV2\GiftItem::class);
        $this->gift_list = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool switch = 11;</code>
     * @return bool
     */
    public function getSwitch()
    {
        return $this->switch;
    }

    /**
     * Generated from protobuf field <code>bool switch = 11;</code>
     * @param bool $var
     * @return $this
     */
    public function setSwitch($var)
    {
        GPBUtil::checkBool($var);
        $this->switch = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 test = 12;</code>
     * @return int|string
     */
    public function getTest()
    {
        return $this->test;
    }

    /**
     * Generated from protobuf field <code>int64 test = 12;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTest($var)
    {
        GPBUtil::checkInt64($var);
        $this->test = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.WealthInfo wealth_info = 13;</code>
     * @return \app\Protobuf\SendGiftV2\WealthInfo|null
     */
    public function getWealthInfo()
    {
        return $this->wealth_info;
    }

    public function hasWealthInfo()
    {
        return isset($this->wealth_info);
    }

    public function clearWealthInfo()
    {
        unset($this->wealth_info);
    }

    /**
     * Generated from protobuf field <code>.WealthInfo wealth_info = 13;</code>
     * @param \app\Protobuf\SendGiftV2\WealthInfo $var
     * @return $this
     */
    public function setWealthInfo($var)
    {
        GPBUtil::checkMessage($var, \app\Protobuf\SendGiftV2\WealthInfo::class);
        $this->wealth_info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.GroupMedalBrief group_medal = 14;</code>
     * @return \app\Protobuf\SendGiftV2\GroupMedalBrief|null
     */
    public function getGroupMedal()
    {
        return $this->group_medal;
    }

    public function hasGroupMedal()
    {
        return isset($this->group_medal);
    }

    public function clearGroupMedal()
    {
        unset($this->group_medal);
    }

    /**
     * Generated from protobuf field <code>.GroupMedalBrief group_medal = 14;</code>
     * @param \app\Protobuf\SendGiftV2\GroupMedalBrief $var
     * @return $this
     */
    public function setGroupMedal($var)
    {
        GPBUtil::checkMessage($var, \app\Protobuf\SendGiftV2\GroupMedalBrief::class);
        $this->group_medal = $var;

        return $this;
    }

    /**
     * bytes    unknown16 = 16;
     * bytes    unknown17 = 17;
     * bytes    unknown18 = 18;
     * bytes    unknown19 = 19;
     * bytes    unknown20 = 20;
     * bytes    unknown21 = 21;
     * bytes    unknown22 = 22;
     * bytes    unknown23 = 23;
     * bytes    unknown24 = 24;
     * bytes    unknown25 = 25;
     * bytes    unknown26 = 26;
     * bytes    unknown27 = 27;
     * bytes    unknown28 = 28;
     * bytes    unknown29 = 29;
     * bytes    unknown30 = 30;
     * bytes    unknown31 = 31;
     * bytes    unknown32 = 32;
     *
     * Generated from protobuf field <code>.UserInfo sender_uinfo = 15;</code>
     * @return \app\Protobuf\SendGiftV2\UserInfo|null
     */
    public function getSenderUinfo()
    {
        return $this->sender_uinfo;
    }

    public function hasSenderUinfo()
    {
        return isset($this->sender_uinfo);
    }

    public function clearSenderUinfo()
    {
        unset($this->sender_uinfo);
    }

    /**
     * bytes    unknown16 = 16;
     * bytes    unknown17 = 17;
     * bytes    unknown18 = 18;
     * bytes    unknown19 = 19;
     * bytes    unknown20 = 20;
     * bytes    unknown21 = 21;
     * bytes    unknown22 = 22;
     * bytes    unknown23 = 23;
     * bytes    unknown24 = 24;
     * bytes    unknown25 = 25;
     * bytes    unknown26 = 26;
     * bytes    unknown27 = 27;
     * bytes    unknown28 = 28;
     * bytes    unknown29 = 29;
     * bytes    unknown30 = 30;
     * bytes    unknown31 = 31;
     * bytes    unknown32 = 32;
     *
     * Generated from protobuf field <code>.UserInfo sender_uinfo = 15;</code>
     * @param \app\Protobuf\SendGiftV2\UserInfo $var
     * @return $this
     */
    public function setSenderUinfo($var)
    {
        GPBUtil::checkMessage($var, \app\Protobuf\SendGiftV2\UserInfo::class);
        $this->sender_uinfo = $var;

        return $this;
    }

}

