<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SEND_GIFT_V2.proto

namespace app\Protobuf\SendGiftV2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>UserInfo</code>
 */
class UserInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 uid = 1;</code>
     */
    protected $uid = 0;
    /**
     * Generated from protobuf field <code>.Base base = 2;</code>
     */
    protected $base = null;
    /**
     *   Wealth wealth = 4;
     *
     * Generated from protobuf field <code>.Medal medal = 3;</code>
     */
    protected $medal = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $uid
     *     @type \app\Protobuf\SendGiftV2\Base $base
     *     @type \app\Protobuf\SendGiftV2\Medal $medal
     *             Wealth wealth = 4;
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SENDGIFTV2::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 uid = 1;</code>
     * @return int|string
     */
    public function getUid()
    {
        return $this->uid;
    }

    /**
     * Generated from protobuf field <code>int64 uid = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUid($var)
    {
        GPBUtil::checkInt64($var);
        $this->uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Base base = 2;</code>
     * @return \app\Protobuf\SendGiftV2\Base|null
     */
    public function getBase()
    {
        return $this->base;
    }

    public function hasBase()
    {
        return isset($this->base);
    }

    public function clearBase()
    {
        unset($this->base);
    }

    /**
     * Generated from protobuf field <code>.Base base = 2;</code>
     * @param \app\Protobuf\SendGiftV2\Base $var
     * @return $this
     */
    public function setBase($var)
    {
        GPBUtil::checkMessage($var, \app\Protobuf\SendGiftV2\Base::class);
        $this->base = $var;

        return $this;
    }

    /**
     *   Wealth wealth = 4;
     *
     * Generated from protobuf field <code>.Medal medal = 3;</code>
     * @return \app\Protobuf\SendGiftV2\Medal|null
     */
    public function getMedal()
    {
        return $this->medal;
    }

    public function hasMedal()
    {
        return isset($this->medal);
    }

    public function clearMedal()
    {
        unset($this->medal);
    }

    /**
     *   Wealth wealth = 4;
     *
     * Generated from protobuf field <code>.Medal medal = 3;</code>
     * @param \app\Protobuf\SendGiftV2\Medal $var
     * @return $this
     */
    public function setMedal($var)
    {
        GPBUtil::checkMessage($var, \app\Protobuf\SendGiftV2\Medal::class);
        $this->medal = $var;

        return $this;
    }

}

